"""North Carolina FAQ page, About, Privacy, Terms."""
FAQ_PAGE = [
    ("How much does it cost to work with ECOS Medicare Solutions?", "Nothing. Independent Medicare agents are paid by the insurance carriers when you enroll, so comparing plans, answering questions and reviewing your coverage each year is free to you. Your premium is the same whether you enroll through us, another agent or the carrier directly."),
    ("My hospital left my Medicare Advantage plan&rsquo;s network. What now?", "Check which it is: a hospital leaving a network, or a plan leaving your county. For 2026 UNC Health left Humana, WellCare and HCSC (Cigna) Advantage networks and CarolinaEast in New Bern left Blue Cross NC&rsquo;s on July 1. A network change is fixed in the Annual Election Period (October 15 to December 7) or, for current Advantage members, January 1 to March 31; it does not by itself create a guaranteed-issue right to Medigap. A plan withdrawing from your county does, generally within 63 days of the coverage ending."),
    ("Does North Carolina have a Medigap birthday rule or annual switching window?", "No. Your six-month Medigap open enrollment at 65 is the guaranteed window, plus federal guaranteed-issue events such as a plan leaving your county or the twelve-month Advantage trial right. Outside those, North Carolina insurers can use medical underwriting."),
    ("I am under 65 on Medicare because of a disability. Can I buy Medigap in North Carolina?", "Yes. North Carolina law (G.S. 58-54-45) guarantees you Plan A, D or G during a six-month window that starts when Part B begins. Premiums may be higher than at 65 and a pre-existing-condition wait of up to six months can apply unless you had creditable coverage. You get a fresh open enrollment for every plan at 65."),
    ("Does Duke or UNC accept Medicare Advantage plans?", "Both accept Original Medicare and therefore every Medigap policy. Each contracts with some Medicare Advantage plans and not others, and the list changes yearly &mdash; for 2026 UNC Health is out of network with Humana, WellCare and HCSC (Cigna) plans. If Duke, UNC, Atrium, Novant, WakeMed, Cone, ECU Health or Mission is your care, we confirm the plan&rsquo;s status in writing before you enroll."),
    ("I am on the State Health Plan&rsquo;s Humana Medicare Advantage plan. Should I stay on it?", "Nearly 177,000 retired state employees and teachers are. The group plan kept in-network access to UNC Health when individual Humana plans lost it, and its 2027 out-of-pocket changes were approved in June 2026. Whether to stay or move to an individual plan depends on your doctors, your drugs and the State Health Plan&rsquo;s rules on leaving; we walk through it with the plan documents in front of us."),
    ("I just moved to North Carolina. Does my plan from Ohio or New Jersey work here?", "A Medigap policy with Original Medicare works anywhere in the U.S. and comes with you. Most Medicare Advantage and Part D plans end when you leave their service area, and the move opens a Special Enrollment Period to pick a plan sold in your new county. See our Moving to North Carolina guide."),
    ("I have TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating the drug benefit. Our Fort Bragg, Camp Lejeune and Seymour Johnson pages walk through it."),
    ("I use the VA. Do I still need Medicare Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying it triggers a permanent penalty and leaves you without coverage at a non-VA hospital. VA pharmacy is creditable for Part D."),
    ("When can I enroll in or change my Medicare plan in North Carolina?", "Your Initial Enrollment Period is the seven months around your 65th birthday. The Annual Election Period runs October 15 to December 7; Medicare Advantage Open Enrollment runs January 1 to March 31. Moving here or between counties, losing a plan, qualifying for Medicaid, or a FEMA-declared disaster opens a Special Enrollment Period."),
    ("Is there still a Hurricane Helene enrollment period?", "No. The disaster Special Enrollment Period for the 25 declared western counties ended February 16, 2025. The rule behind it stands for any future FEMA declaration in North Carolina: people in the declared area who missed another enrollment window get one through two months after the incident period ends."),
    ("What are the [[YEAR]] Medicare costs?", "Part B premium $202.90 a month, Part B deductible $283, Part A hospital deductible $1,736 per benefit period, Part D out-of-pocket cap $2,100. Higher earners pay IRMAA surcharges above $109,000 (single) or $218,000 (joint) of 2024 income. Our costs page has the full chart and calculators."),
    ("Can North Carolina help pay my Part B premium?", "Possibly. North Carolina&rsquo;s Medicare Savings Programs &mdash; MQB-Q, MQB-B and MQB-E, the state&rsquo;s names for QMB, SLMB and QI &mdash; pay the Part B premium for people with limited income and resources, and MQB-Q also covers Medicare&rsquo;s deductibles and copays. Apply at ePASS or your county Department of Social Services, or call NC SHIIP at 855-408-1212."),
    ("If I have both Medicare and NC Medicaid, am I in a managed-care plan?", "Not a Standard Plan; people with both are served through NC Medicaid Direct. Those with significant behavioral-health, I/DD or TBI needs may be in a Tailored Plan. Medicare pays first either way, and a Dual Special Needs Plan on the Medicare side can coordinate the two."),
    ("Where can I get free, unbiased Medicare counseling in North Carolina?", "NC SHIIP, the Seniors&rsquo; Health Insurance Information Program, is a division of the North Carolina Department of Insurance and North Carolina&rsquo;s State Health Insurance Assistance Program: 855-408-1212, with volunteer counselors in all 100 counties. You can also call 1-800-MEDICARE or use Medicare.gov. We are an independent agency, not a government program, and we say so on every page."),
    ("Do you offer every plan available in my area?", "No. We represent a number of insurance organizations and products in North Carolina, not all of them, and we will always say so. For the complete list, use Medicare.gov, 1-800-MEDICARE or NC SHIIP. For help choosing among the plans we do offer, call [[PHONE]]."),
    ("Where can I verify your North Carolina licence?", "Darin Weidauer holds North Carolina insurance license #18580338 (NPN 18580338). You can verify it through the North Carolina Department of Insurance licensee lookup at ncdoi.gov or through the NIPR."),
    ("Do you meet in person?", "We work with North Carolinians statewide by phone and video, which is how most people prefer it across a state this long. Our sister agency has walk-in offices in Mesa and Sun City, Arizona."),
]

ABOUT_BODY = """<div class="author" style="margin-bottom:2rem">
<img class="author__photo" src="/darin.jpg" width="600" height="600" alt="Darin Weidauer, independent Medicare insurance agent and credentialed gerontologist" loading="lazy" decoding="async">
<div>
<ul class="creds"><li>NC License #18580338 · NPN 18580338</li><li>Credentialed gerontologist (2014)</li><li>Registered Social Security Analyst&reg;</li><li>MBA, Pepperdine</li><li>Master&rsquo;s in Long-Term Care, USC</li><li>22-yr USAF veteran (retired officer)</li></ul>
<p>Darin Weidauer is an independent Medicare insurance agent, credentialed gerontologist, and Registered Social Security Analyst&reg; who helps North Carolina retirees and people approaching 65 make sense of their Medicare options &mdash; clearly, patiently, and with no cost to them.</p>
</div></div>
<h2>Background</h2>
<p>A 22-year U.S. Air Force veteran who retired as an officer, Darin holds five master&rsquo;s degrees, including an MBA and a Master&rsquo;s in Dispute Resolution from Pepperdine University and a Master&rsquo;s in Long-Term Care from the University of Southern California&rsquo;s Leonard Davis School of Gerontology, where he became a credentialed gerontologist in 2014 &mdash; studying the human side of aging, not just the paperwork.</p>
<p>A former Professor of Aerospace Studies at Loyola Marymount University who has lectured at more than 50 colleges and universities, Darin now channels that teaching instinct into plain-English Medicare education: one-on-one reviews, no-cost community workshops, the free 295-page guide <a href="/retirement-guide"><em>Retire With Confidence</em></a>, and the pages on this site, every one of which he wrote or reviewed. He is also the founder of MyECOS360, an agency operating system for independent insurance agents, and the author of its training on <a href="https://www.myecos360.com/insurance-lead-economics">insurance lead economics</a>.</p>
<h2>How he is paid, and what that means for you</h2>
<p>ECOS Medicare Solutions is an independent agency: appointed with a number of Medicare Advantage, Medigap and Part D carriers in North Carolina, employed by none of them. When you enroll in a plan through us, the carrier pays us a commission. That commission comes out of the carrier&rsquo;s filed rate &mdash; it is never added to your premium. You pay the same whether you enroll through us, through another agent, or directly with the insurer; going direct does not make a policy cheaper, and using us does not make it dearer.</p>
<p>We do not represent every plan sold in North Carolina, and we say so on every page. For a complete list, use Medicare.gov, 1-800-MEDICARE, or NC SHIIP (855-408-1212), the state&rsquo;s free and independent counseling program run by the North Carolina Department of Insurance.</p>
<h2>Licensing</h2>
<p>Darin Weidauer holds <strong>North Carolina insurance license #18580338</strong> and is a licensed insurance agent in North Carolina and fifteen other states &mdash; Arizona, California, Colorado, Georgia, Hawaii, Indiana, Minnesota, Nevada, New Mexico, Ohio, South Carolina, Tennessee, Texas, Utah and Washington &mdash; under National Producer Number 18580338, which you can verify with the North Carolina Department of Insurance&rsquo;s licensee lookup or the NIPR. The multi-state licence is what lets us follow retirees who <a href="/moving-to-north-carolina">move to North Carolina</a> from Ohio, Indiana or Tennessee, and North Carolinians to their second homes across the line in South Carolina and Georgia.</p>
<h2>Where else you will find him</h2>
<ul>
<li><a href="https://www.myecos360.com/darin-weidauer" rel="noopener">Author page at MyECOS360</a> &mdash; the canonical profile</li>
<li><a href="https://www.linkedin.com/in/darin-weidauer-3165a816b/" rel="noopener">LinkedIn</a> and <a href="https://www.youtube.com/channel/UCD1XkkknhQ3UT-8AteYD3vQ" rel="noopener">YouTube</a></li>
<li>Sister sites: <a href="https://www.ecosinsurancesolutions.com/south-carolina" rel="noopener">South Carolina Medicare Enrollment</a>, <a href="https://www.ecosinsurancesolutions.com/tennessee" rel="noopener">Tennessee Medicare Quotes</a>, <a href="https://www.ecosinsurancesolutions.com/georgia" rel="noopener">Georgia Medicare Enrollment</a>, <a href="https://www.ecosinsurancesolutions.com/texas" rel="noopener">Texas Medicare Enrollment</a>, and <a href="https://www.mymedigaprate.com" rel="noopener">MyMedigapRate</a>, where Medigap rate filings &mdash; North Carolina&rsquo;s included &mdash; are published filing by filing.</li>
</ul>
<h2>How to reach him</h2>
<p>Call <a href="tel:[[TEL]]"><strong>[[PHONE]]</strong></a>, email <a href="mailto:[[EMAIL]]">[[EMAIL]]</a>, or use the form at the top of this page. We work with North Carolinians statewide by phone and video.</p>
"""

PRIVACY_BODY = """<p style="color:var(--ink-soft)"><em>Last updated: September 13, 2026. This policy is provided as a starting template and should be reviewed by your attorney before launch.</em></p>
<p>This Privacy Policy explains how ECOS Medicare Solutions ("we," "us") handles information collected through the North Carolina section of ecosinsurancesolutions.com (the "Site").</p>
<h2>Information we collect</h2>
<p>When you submit a form on the Site, we collect the information you provide: your name, phone number, email address, ZIP code or city, the topic you select, and a record of the consent you give (including the consent language shown and a date/time stamp). We do not ask for, and ask you not to send, health information through the form.</p>
<h2>How we use it</h2>
<p>We use your information to contact you about Medicare plan options and to provide the help you requested &mdash; by phone call, text message and email, consistent with the consent you provide. A licensed insurance agent may contact you. We do not sell your personal information.</p>
<h2>How your form is processed</h2>
<p>Our forms are delivered through a third-party form-processing service (Web3Forms), which transmits your submission to us. The Site loads web fonts from Google Fonts. We aim to limit data sharing to what is needed to operate the Site and respond to you.</p>
<h2>Analytics</h2>
<p>When enabled, we use Google Analytics to understand how visitors find and use this Site &mdash; which pages are read, and whether people call or submit a form. Google Analytics sets cookies and receives your IP address, device and browser type, and the pages you view. We use it in aggregate to improve the Site.</p><p>We do not send Google Analytics your name, phone number, email address or any information you type into a form. You can opt out across all sites using Google&rsquo;s <a href="https://tools.google.com/dlpage/gaoptout" rel="nofollow noopener" target="_blank">browser opt-out add-on</a>, or by using your browser&rsquo;s cookie controls.</p>
<h2>Your choices</h2>
<p>You can opt out of further contact at any time by telling us, replying STOP to texts, or unsubscribing from emails. To request that we delete your information, contact us using the details below.</p>
<h2>Data security</h2>
<p>We take reasonable measures to protect the information you share, but no method of transmission over the internet is completely secure. If a security breach affects your personal information, we will notify you as North Carolina&rsquo;s Identity Theft Protection Act requires.</p>
<h2>Children</h2>
<p>The Site is intended for adults making Medicare decisions and is not directed to children under 13.</p>
<h2>Contact us</h2>
<p>Questions about this policy? Call <a href="tel:[[TEL]]"><strong>[[PHONE]]</strong></a>, email <a href="mailto:[[EMAIL]]">[[EMAIL]]</a>, or use the form on our <a href="/">home page</a>.</p>
<p style="font-size:.85rem;color:var(--ink-soft)">ECOS Medicare Solutions is not connected with or endorsed by the U.S. government or the federal Medicare program. This is a solicitation for insurance.</p>
"""

TERMS_BODY = """<p style="color:var(--ink-soft)"><em>Last updated: September 13, 2026. This document is provided as a starting template and should be reviewed by your attorney before launch.</em></p>
<p>By using the North Carolina section of ecosinsurancesolutions.com (the "Site"), operated by ECOS Medicare Solutions, you agree to these Terms of Use.</p>
<h2>Informational purpose</h2>
<p>The Site provides general information about Medicare to help you make decisions. It is not legal, tax or medical advice, and it is not a substitute for the official Medicare program or for North Carolina&rsquo;s free counseling program, the Seniors&rsquo; Health Insurance Information Program (SHIIP) of the North Carolina Department of Insurance. Medicare plan availability, costs and rules change and vary by county.</p>
<h2>Insurance offered through a licensed agent</h2>
<p>Insurance products referenced on the Site are offered through a licensed insurance agent (Darin Weidauer, North Carolina insurance license #18580338, NPN 18580338). Enrollment is subject to plan terms and eligibility. We do not offer every plan available in your area.</p>
<h2>No guarantee of accuracy</h2>
<p>We work to keep figures current and cite the year and source, but we do not warrant that all information is complete, current or error-free. Always confirm details with the official sources noted on the Site.</p>
<h2>External links</h2>
<p>The Site links to third-party websites (such as Medicare.gov, ncdoi.gov and medicaid.ncdhhs.gov) and to other sites operated by ECOS Medicare Solutions. We are not responsible for the content or practices of third-party sites.</p>
<h2>Limitation of liability</h2>
<p>To the fullest extent permitted by law, ECOS Medicare Solutions is not liable for any damages arising from your use of the Site.</p>
<h2>Governing law</h2>
<p>These Terms are governed by the laws of the State of North Carolina.</p>
<h2>Contact us</h2>
<p>Questions? Call <a href="tel:[[TEL]]"><strong>[[PHONE]]</strong></a> or use the form on our <a href="/">home page</a>.</p>
<p style="font-size:.85rem;color:var(--ink-soft)">ECOS Medicare Solutions is not connected with or endorsed by the U.S. government or the federal Medicare program. This is a solicitation for insurance.</p>
"""
