"""New Mexico regions, cities and military communities."""
COST = "Nothing. Independent agents are paid by the carriers when you enroll, so comparing plans and reviewing your coverage each year is free to you."
EXIT = ("Presbyterian Health Plan announced in June 2026 that it will discontinue most of its Medicare Advantage plans for 2027, keeping only its Dual Plus plan for people who also have Medicaid. Your 2026 coverage runs through December 31. "
        "A plan leaving you involuntarily gives you the Annual Election Period (Oct 15&ndash;Dec 7) to choose, a Special Enrollment Period if you need it, and in most cases a guaranteed-issue right to a Medigap policy without health questions for a limited window around the date the coverage ends.")
FAR = ("Often Original Medicare with a Medigap policy, because it has no network: the local hospital, the Albuquerque specialist and an out-of-state referral are all covered the same way. "
       "An Advantage plan can work if its network genuinely reaches the providers you use; we check the nearest in-network specialists, not just whether the plan is sold in your county, before you enroll.")

REGIONS = [
    dict(slug="albuquerque-metro", name="Albuquerque Metro", short="the Albuquerque area", scene="sandia",
         eyebrow="Medicare by region · Albuquerque, Rio Rancho, Los Lunas &amp; the East Mountains",
         h1="Medicare help across the Albuquerque metro",
         sub="Bernalillo, Sandoval, Valencia and Torrance counties &mdash; the deepest plan menu in New Mexico, three hospital systems that contract separately, the Raymond G. Murphy VA, Kirtland AFB, and a home-grown Advantage carrier leaving the market for 2027.",
         counties="Bernalillo, Sandoval, Valencia, Torrance",
         cities=["albuquerque", "rio-rancho", "los-lunas", "kirtland-afb"],
         systems=["Presbyterian Healthcare Services", "UNM Health", "Lovelace Health System", "Presbyterian Rust Medical Center (Rio Rancho)", "UNM Sandoval Regional Medical Center (Rio Rancho)", "Raymond G. Murphy VA Medical Center"],
         note="<p><strong>Local plans to know:</strong> Presbyterian Health Plan, built on the Presbyterian system, sold Advantage plans here for years; it announced in June 2026 that it is discontinuing most of them for 2027 and keeping only its Dual Plus plan. Blue Cross and Blue Shield of New Mexico and the national carriers sell across the metro, and each contracts with Presbyterian, UNM and Lovelace on its own terms. If your doctor sits inside one system, that decides the shortlist before premiums do.</p>",
         intro=["Roughly half of New Mexico&rsquo;s Medicare population lives within an hour of downtown Albuquerque, and the plan menu shows it: the widest Advantage choice in the state, every Medigap carrier licensed in New Mexico, and the full Part D lineup. The trade-off is that the metro&rsquo;s care is organized into three systems that contract separately &mdash; Presbyterian, UNM Health and Lovelace &mdash; so a $0-premium plan that includes Presbyterian Hospital may exclude UNM, or the reverse.",
                "The other thing shaping this fall is Presbyterian&rsquo;s decision to leave most of the Advantage market for 2027, which puts about 30,000 members statewide, many of them here, back in the market during the Annual Election Period. Valencia County adds a wrinkle of its own: it has no hospital, so Los Lunas and Belen residents drive to Albuquerque, and a plan&rsquo;s network has to include the systems they actually use."],
         faqs=[("Which Medicare plans are available in Albuquerque?", "Bernalillo County typically has the widest choice in New Mexico: Medicare Advantage plans from Blue Cross and Blue Shield of New Mexico and the national carriers (and, through 2026, Presbyterian Health Plan), every Medigap carrier in the state, and all standalone Part D plans. Availability is set by county and ZIP code and changes each plan year."),
               ("Presbyterian is ending my Advantage plan. What now?", EXIT),
               ("How much does your help cost?", COST)]),
    dict(slug="santa-fe-north-central", name="Santa Fe &amp; North Central New Mexico", short="Santa Fe and the north", scene="adobe",
         eyebrow="Medicare by region · Santa Fe, Los Alamos, Espa&ntilde;ola &amp; Taos",
         h1="Medicare help across Santa Fe and north central New Mexico",
         sub="Santa Fe, Los Alamos, Rio Arriba and Taos counties &mdash; Christus St. Vincent, the labs&rsquo; retirees, a Critical Access Hospital in Taos, and the mountain villages where the nearest specialist is in Santa Fe or Albuquerque.",
         counties="Santa Fe, Los Alamos, Rio Arriba, Taos",
         cities=["santa-fe", "los-alamos", "taos"],
         systems=["Christus St. Vincent Regional Medical Center (Santa Fe)", "Presbyterian Santa Fe Medical Center", "Los Alamos Medical Center", "Holy Cross Medical Center (Taos)", "UNM Health and Presbyterian (Albuquerque referrals)"],
         note="<p><strong>What to watch:</strong> Santa Fe County has a moderate Advantage menu and two hospitals that contract with different plans. Los Alamos retirees often carry lab or federal retiree coverage that changes the Part B decision. Taos and Rio Arriba rely on small hospitals and on Santa Fe and Albuquerque for anything more, which is where a Medigap policy&rsquo;s any-provider access earns its premium.</p>",
         intro=["Santa Fe is where much of New Mexico retires to, and its Medicare market is built around Christus St. Vincent, the largest hospital north of Albuquerque, with Presbyterian&rsquo;s Santa Fe campus as the second choice. The Advantage menu is real but narrower than Albuquerque&rsquo;s, and Presbyterian&rsquo;s exit for 2027 narrows it again, so the comparison against Original Medicare with a Medigap policy is a live one here.",
                "North of the city the map changes fast. Los Alamos has its own 47-bed hospital and a large population of lab retirees; Taos has a 25-bed Critical Access Hospital; and the villages of Rio Arriba and the high country look to Espa&ntilde;ola, Santa Fe or Albuquerque for specialty care, an hour or two each way. We compare what is sold at your ZIP code against the roads you actually drive."],
         faqs=[("Which Medicare plans are available in Santa Fe?", "Santa Fe County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup. Los Alamos, Rio Arriba and Taos counties have fewer Advantage plans. We compare what is sold at your address."),
               ("Is Christus St. Vincent in my plan&rsquo;s network?", "Christus St. Vincent accepts Original Medicare, and therefore any Medigap policy. It contracts with some Medicare Advantage plans and not others, and the list changes yearly. We confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="northwest-four-corners", name="Northwest &amp; the Four Corners", short="the Four Corners", scene="shiprock",
         eyebrow="Medicare by region · Farmington, Gallup, Grants &amp; the Navajo Nation",
         h1="Medicare help across northwest New Mexico and the Four Corners",
         sub="San Juan, McKinley and Cibola counties &mdash; San Juan Regional in Farmington, Rehoboth McKinley and Gallup Indian Medical Center in Gallup, and the largest share of the state&rsquo;s Medicare beneficiaries whose care runs through the Indian Health Service.",
         counties="San Juan, McKinley, Cibola",
         cities=["farmington", "gallup"],
         systems=["San Juan Regional Medical Center (Farmington)", "Rehoboth McKinley Christian Health Care Services (Gallup)", "Gallup Indian Medical Center (IHS)", "Raymond G. Murphy VA Medical Center (Albuquerque)"],
         note="<p><strong>What to watch:</strong> A large share of the region&rsquo;s Medicare beneficiaries are members of the Navajo Nation, the Pueblos of Zuni, Acoma and Laguna and other tribes whose primary care runs through IHS and tribal facilities. The IHS is not insurance and its referral program is the payer of last resort, so Medicare enrollment matters here, and whether an Advantage plan lists your IHS hospital in its network is the first question to ask. Farmington families also cross into Colorado for care, which a Medigap policy covers and an Advantage network may not.</p>",
         intro=["The Four Corners is New Mexico&rsquo;s clearest case of distance shaping the plan choice. San Juan Regional Medical Center in Farmington is the region&rsquo;s trauma center and the referral point for everything from Shiprock to Aztec; Gallup has Rehoboth McKinley and the IHS&rsquo;s Gallup Indian Medical Center; Grants has a small hospital; and the reservation chapters between them are an hour or more from any of it. For a cardiologist or an oncologist, most of the region drives to Albuquerque, and many Farmington families drive north to Durango or Denver instead.",
                "Medicare and the Indian Health Service fit together better than most people assume: IHS encourages eligible tribal members to enroll, Medicare pays IHS and tribal facilities for covered care, and it pays for the referrals the IHS cannot fund. Our <a href=\"/rural-new-mexico\">rural New Mexico guide</a> lays it out with the federal sources."],
         faqs=[("Which Medicare plans are available in Farmington and Gallup?", "San Juan and McKinley counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup. Cibola County has fewer Advantage plans. Availability is set by county and changes each plan year."),
               ("I get my care at an IHS hospital. Do I still need Medicare?", "The IHS says it is not health insurance and that its Purchased/Referred Care program is the payer of last resort, and it encourages eligible tribal members to enroll in Medicare. Enrolling does not affect your IHS eligibility, it pays the facility for your care, and it covers care the facility cannot provide. Enroll in Part B on time."),
               ("How much does your help cost?", COST)]),
    dict(slug="northeast-high-plains", name="Northeast &amp; the High Plains", short="the northeast", scene="plains",
         eyebrow="Medicare by region · Las Vegas, Raton, Clayton, Tucumcari &amp; Santa Rosa",
         h1="Medicare help across northeast New Mexico and the high plains",
         sub="Colfax, Union, Mora, Harding, San Miguel, Guadalupe and Quay counties &mdash; small county hospitals, counties with none at all, and a road to Santa Fe, Albuquerque or Amarillo for nearly everything else.",
         counties="Colfax, Union, Mora, Harding, San Miguel, Guadalupe, Quay",
         cities=[],
         systems=["Christus St. Vincent Regional Medical Center (Santa Fe)", "UNM Hospital (Albuquerque)", "Presbyterian Hospital (Albuquerque)", "Small county and Critical Access Hospitals in the region"],
         note="<p><strong>What to watch:</strong> This is the part of New Mexico where the state&rsquo;s Rural Health Plan found counties with no hospital at all, and where the hospitals that exist are small Critical Access Hospitals. Advantage menus are short, and a plan sold in your county may have no in-network specialist for 150 miles. Original Medicare with a Medigap policy covers the county hospital, Santa Fe, Albuquerque and Amarillo alike, and that is often the practical answer out here.</p>",
         intro=["The northeast is ranch and railroad country, and its Medicare market is small and spread out: Las Vegas, Raton, Clayton, Tucumcari and Santa Rosa each anchor a county, several of the counties between them have no hospital, and the 2022 Hermits Peak and Calf Canyon fires displaced whole communities in Mora and San Miguel counties. Specialty care means Santa Fe or Albuquerque for most of the region, and Amarillo for the eastern edge.",
                "That is why the plan-type question matters more here than the premium. We map a plan&rsquo;s network against the way you actually get care &mdash; the clinic in town, the county hospital, the specialist two hours away &mdash; and set an Advantage plan beside a Medigap policy so the trade-off is plain. If a FEMA-declared disaster ever keeps you from enrolling on time, Medicare gives you a Special Enrollment Period afterward."],
         faqs=[("Which Medicare plans are available in the northeast?", "Colfax, San Miguel, Quay and the surrounding counties typically offer a short Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup. Availability is set by county and changes each plan year; some counties have very few Advantage plans."),
               ("I live two hours from a specialist. Which plan makes sense?", FAR),
               ("How much does your help cost?", COST)]),
    dict(slug="las-cruces-southwest", name="Las Cruces &amp; the Southwest", short="Las Cruces and the southwest", scene="organ",
         eyebrow="Medicare by region · Las Cruces, Deming, Silver City, Truth or Consequences &amp; the bootheel",
         h1="Medicare help across Las Cruces and southwest New Mexico",
         sub="Do&ntilde;a Ana, Luna, Grant, Hidalgo and Sierra counties &mdash; the state&rsquo;s second-largest Medicare market, three Las Cruces hospitals, White Sands Missile Range retirees, and El Paso forty minutes down I-10.",
         counties="Do&ntilde;a Ana, Luna, Grant, Hidalgo, Sierra",
         cities=["las-cruces", "deming", "silver-city"],
         systems=["MountainView Regional Medical Center (Las Cruces)", "Memorial Medical Center (Las Cruces)", "Three Crosses Regional Hospital (Las Cruces)", "Mimbres Valley Medical Center (Deming)", "Gila Regional Medical Center (Silver City)", "El Paso hospitals (Texas referrals)"],
         note="<p><strong>What to watch:</strong> Do&ntilde;a Ana County has a deep Advantage menu and three hospitals that contract differently. The bigger question is El Paso: many Las Cruces, Deming and Silver City families see specialists there, and whether a New Mexico Advantage plan&rsquo;s network reaches across the state line decides more than the premium does. A Medigap policy has no state line.</p>",
         intro=["Las Cruces is the second-biggest Medicare market in New Mexico and, in practice, half of a larger one shared with El Paso. MountainView Regional, Memorial Medical Center and the newer Three Crosses Regional each contract with some Advantage plans and not others, and a large share of the region&rsquo;s specialty care happens forty minutes south in Texas. White Sands Missile Range retirees add a TRICARE For Life layer that changes the calculation entirely.",
                "West of the Rio Grande the menu thins. Deming and Silver City each have a 25-bed Critical Access Hospital, Truth or Consequences a small one, and Hidalgo County&rsquo;s bootheel is as far from a hospital as anywhere in the state; Tucson is the referral city for some of it. Our <a href=\"https://www.ecosinsurancesolutions.com/texas/el-paso\">El Paso page</a> covers the view from the Texas side."],
         faqs=[("Which Medicare plans are available in Las Cruces?", "Do&ntilde;a Ana County typically offers a deep Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup. Luna, Grant, Hidalgo and Sierra counties have fewer Advantage plans. We compare what is sold at your address."),
               ("Can I see a doctor in El Paso with a New Mexico plan?", "With Original Medicare and a Medigap policy, yes, anywhere in the country. With a Medicare Advantage plan, only if the El Paso provider is in that plan&rsquo;s network or the plan covers out-of-network care, which we confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="southeast-permian", name="Southeast &amp; the Permian Basin", short="the southeast", scene="plains",
         eyebrow="Medicare by region · Roswell, Carlsbad, Hobbs, Artesia &amp; Lovington",
         h1="Medicare help across southeast New Mexico and the Permian Basin",
         sub="Chaves, Eddy and Lea counties &mdash; oil-patch retirees with royalty income, four regional hospitals, and Lubbock or Midland as the referral cities for anything they cannot do.",
         counties="Chaves, Eddy, Lea",
         cities=["roswell", "carlsbad", "hobbs", "artesia"],
         systems=["Eastern New Mexico Medical Center (Roswell)", "Lovelace Regional Hospital (Roswell)", "Carlsbad Medical Center", "Lea Regional Medical Center (Hobbs)", "Nor-Lea General Hospital (Lovington)", "Artesia General Hospital"],
         note="<p><strong>What to watch:</strong> The Permian counties have moderate Advantage menus and a different IRMAA problem from the rest of the state: a strong year of oil-and-gas royalties or a mineral-rights sale shows up in your Part B premium two years later. Many southeast families see specialists in Lubbock or Midland, which a Medigap policy covers and an Advantage network may not.</p>",
         intro=["Southeast New Mexico looks east as much as north. Roswell&rsquo;s Eastern New Mexico Medical Center is the region&rsquo;s Level III trauma center and Lovelace runs a second hospital there; Carlsbad, Hobbs, Lovington and Artesia each have their own; and for a cardiac surgeon or a cancer center many families drive to Lubbock or Midland rather than Albuquerque. Whether a plan&rsquo;s network reaches into Texas is therefore a real question, and a Medigap policy answers it without a network.",
                "The Permian&rsquo;s royalty economy adds an income wrinkle: IRMAA is a cliff, and a good year in 2024 can raise your 2026 Medicare premium. Our <a href=\"/medicare-costs\">costs page</a> has the chart and the appeal form to ask for."],
         faqs=[("Which Medicare plans are available in Roswell, Carlsbad and Hobbs?", "Chaves, Eddy and Lea counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup. Availability is set by county and changes each plan year."),
               ("Can I use Lubbock or Midland specialists with a New Mexico plan?", "With Original Medicare and a Medigap policy, yes. With an Advantage plan, only if the Texas provider is in that plan&rsquo;s network or the plan covers out-of-network care. We confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="east-clovis-portales", name="East &amp; Clovis&ndash;Portales", short="the Clovis area", scene="plains",
         eyebrow="Medicare by region · Clovis, Portales, Fort Sumner &amp; Cannon AFB",
         h1="Medicare help across Clovis, Portales and eastern New Mexico",
         sub="Curry, Roosevelt and De Baca counties &mdash; Plains Regional Medical Center, Roosevelt General, the Cannon AFB retiree community, and Lubbock and Amarillo an hour and a half east for specialty care.",
         counties="Curry, Roosevelt, De Baca",
         cities=["clovis", "cannon-afb"],
         systems=["Plains Regional Medical Center (Presbyterian, Clovis)", "Roosevelt General Hospital (Portales)", "Cannon AFB 27th Special Operations Medical Group (TRICARE)", "Lubbock and Amarillo hospitals (Texas referrals)"],
         note="<p><strong>What to watch:</strong> Clovis&rsquo;s hospital belongs to Presbyterian, and Presbyterian Health Plan is leaving most of the Advantage market for 2027, so plan networks here are being redrawn this fall. Cannon retirees carry TRICARE For Life, which usually makes a Medigap policy and a Part D plan unnecessary. For anything beyond the regional hospitals, the road runs east into Texas.</p>",
         intro=["Eastern New Mexico shares a time zone with Santa Fe and a referral pattern with West Texas. Plains Regional Medical Center in Clovis, part of the Presbyterian system, and Roosevelt General Hospital in Portales handle most of the region&rsquo;s care; Lubbock and Amarillo are the specialty cities, and De Baca County is an hour from either hospital. That geography is why the plan-type question matters more here than the premium.",
                "Cannon Air Force Base adds a large retiree community with TRICARE For Life, for whom the Medicare decision is mostly about Part B timing and whether an MA-only plan&rsquo;s dental and vision extras are worth having. Our <a href=\"/cannon-afb\">Cannon AFB page</a> walks through it, and our Texas section covers <a href=\"https://www.ecosinsurancesolutions.com/texas/lubbock\">Lubbock</a> and <a href=\"https://www.ecosinsurancesolutions.com/texas/amarillo\">Amarillo</a> from the other side."],
         faqs=[("Which Medicare plans are available in Clovis?", "Curry County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup. Roosevelt and De Baca counties have fewer Advantage plans. Presbyterian&rsquo;s exit for 2027 changes the lineup this fall."),
               ("I have TRICARE For Life from Cannon. Which plan should I look at?", "With TFL you already have a supplement-like layer and creditable drug coverage, so a Medigap policy and a Part D plan are usually unnecessary. An MA-only Advantage plan can add dental or vision without duplicating drug coverage. See our Cannon AFB and Veterans pages."),
               ("How much does your help cost?", COST)]),
    dict(slug="central-mountains", name="Central Mountains &amp; the Tularosa Basin", short="the central mountains", scene="pinon",
         eyebrow="Medicare by region · Alamogordo, Ruidoso, Socorro &amp; Catron County",
         h1="Medicare help across the central mountains and the Tularosa Basin",
         sub="Otero, Lincoln, Socorro and Catron counties &mdash; Gerald Champion in Alamogordo, Lincoln County Medical Center in Ruidoso, Holloman AFB retirees, the Mescalero Apache reservation, and the emptiest county in the state.",
         counties="Otero, Lincoln, Socorro, Catron",
         cities=["alamogordo", "ruidoso", "holloman-afb"],
         systems=["Gerald Champion Regional Medical Center (CHRISTUS, Alamogordo)", "Lincoln County Medical Center (Ruidoso)", "Holloman AFB 49th Medical Group (TRICARE)", "UNM Hospital and Presbyterian (Albuquerque referrals)", "El Paso and Las Cruces hospitals (referrals)"],
         note="<p><strong>What to watch:</strong> Alamogordo&rsquo;s Gerald Champion Regional Medical Center &mdash; shared by Holloman&rsquo;s military community and civilians since 1999, and acquired by CHRISTUS Health effective July 1, 2026 &mdash; anchors the basin; Ruidoso&rsquo;s Lincoln County Medical Center serves the mountain resort towns that fill with Texas retirees. Catron County has no hospital. The 2024 South Fork and Salt fires around Ruidoso displaced thousands of residents, and Medicare gives a Special Enrollment Period to anyone a declared disaster kept from enrolling on time.</p>",
         intro=["The central mountains hold two very different Medicare communities. Alamogordo and the Tularosa Basin are Air Force country, where TRICARE For Life and the VA shape the decision; Ruidoso and Lincoln County are second-home country, where a plan chosen in Lubbock or Midland has to work in the mountains too. Socorro and Catron counties, west across the Rio Grande, are among the emptiest in the state, and a specialist means Albuquerque.",
                "Across all four counties the practical question is the same: does the plan&rsquo;s network reach the hospital you would actually use, and the city you would be referred to &mdash; Albuquerque, Las Cruces or El Paso? A Medigap policy answers yes everywhere; an Advantage plan answers county by county, and we check before you enroll."],
         faqs=[("Which Medicare plans are available in Alamogordo and Ruidoso?", "Otero and Lincoln counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup. Socorro and Catron counties have fewer Advantage plans. We compare what is sold at your address."),
               ("I keep a place in Ruidoso but live in Texas. Which plan covers both?", "Your plan is tied to your permanent residence. A Medigap policy with Original Medicare works in both states; most Advantage HMOs cover only emergencies outside their service area. Our agency is licensed in New Mexico and Texas, so we can compare from either side."),
               ("How much does your help cost?", COST)]),
]

def city(slug, name, county, region, scene, sub, intro, systems, communities, faqs, nearby):
    return dict(slug=slug, name=name, county=county, region=region, scene=scene, sub=sub, intro=intro, systems=systems, communities=communities, faqs=faqs, nearby=nearby)

CITIES = [
    city("albuquerque", "Albuquerque", "Bernalillo County", "albuquerque-metro", "sandia",
         "From the North Valley to the East Mountains, Albuquerque has the deepest Medicare menu in New Mexico &mdash; and, this fall, the biggest reshuffle, as Presbyterian leaves most of the Advantage market for 2027. The comparison here starts with your hospital system.",
         ["Bernalillo County offers the widest Medicare Advantage choice in the state, every Medigap carrier licensed in New Mexico and the full Part D lineup. The catch is that Albuquerque&rsquo;s care is organized into three systems that contract separately: Presbyterian (Presbyterian Hospital and Kaseman), UNM Health (UNM Hospital) and Lovelace (Lovelace Medical Center and the Heart Hospital of New Mexico). A plan that includes Presbyterian may exclude UNM, or the reverse.",
          "Presbyterian Health Plan&rsquo;s decision to discontinue most of its Advantage plans for 2027 puts thousands of Albuquerque members back in the market during the October 15&ndash;December 7 Annual Election Period, with a guaranteed-issue path to Medigap for those who want to leave networks behind. We compare what is actually offered at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a supplement so you can see the trade-off plainly."],
         ["Presbyterian Hospital", "Presbyterian Kaseman Hospital", "UNM Hospital", "Lovelace Medical Center", "Heart Hospital of New Mexico at Lovelace", "Raymond G. Murphy VA Medical Center"],
         "North Valley, South Valley, Nob Hill, the Northeast Heights, Westside, Paradise Hills, Four Hills, Tijeras, Edgewood, Corrales, Bernalillo, Placitas",
         [("Which Medicare plans are available in Albuquerque?", "Bernalillo County typically has the widest choice in New Mexico: Medicare Advantage plans from Blue Cross and Blue Shield of New Mexico and the national carriers (and, through 2026, Presbyterian Health Plan), every Medigap carrier in the state, and all standalone Part D plans. Availability is set by ZIP code and changes each plan year; we compare what is offered at your address."),
          ("Will my Presbyterian, UNM or Lovelace doctors take a Medicare Advantage plan?", "It depends on the specific plan&rsquo;s network, and the contracts change every year &mdash; more than usual for 2027. Before you enroll we confirm your providers are in-network and your prescriptions are on the formulary, so there are no surprises in January."),
          ("How much does your help cost?", COST)],
         ["rio-rancho", "los-lunas", "kirtland-afb", "santa-fe"]),
    city("rio-rancho", "Rio Rancho", "Sandoval County", "albuquerque-metro", "balloons",
         "Rio Rancho, Corrales and Bernalillo have two hospitals of their own &mdash; Presbyterian Rust and UNM Sandoval Regional &mdash; that contract with different plans, plus Albuquerque&rsquo;s full menu across the river.",
         ["Sandoval County residents have the metro&rsquo;s deep Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Presbyterian Rust Medical Center and UNM Sandoval Regional Medical Center, a campus of UNM Hospital, sit a few miles apart and sign their own Advantage contracts, so which one your doctors belong to is the first thing we check.",
          "Presbyterian&rsquo;s exit from most Advantage plans for 2027 lands hard here, where Rust is many families&rsquo; hospital. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy so the trade-off is plain."],
         ["Presbyterian Rust Medical Center", "UNM Sandoval Regional Medical Center", "Presbyterian Hospital (Albuquerque)", "UNM Hospital (Albuquerque)", "Lovelace Medical Center (Albuquerque)"],
         "Rio Rancho, Corrales, Bernalillo, Placitas, Algodones, Enchanted Hills, Mariposa, the Pueblos of Sandoval County",
         [("Which Medicare plans are available in Rio Rancho?", "Sandoval County typically offers a wide Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Presbyterian Rust in my plan&rsquo;s network?", "Rust and UNM Sandoval Regional contract with different Advantage plans, changing year to year, and Presbyterian&rsquo;s own plans end for 2027. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["albuquerque", "los-lunas", "santa-fe"]),
    city("los-lunas", "Los Lunas", "Valencia County", "albuquerque-metro", "bosque",
         "Los Lunas, Belen and Bosque Farms are growing fast, and Valencia County has no hospital &mdash; so a plan&rsquo;s Albuquerque network is the whole question.",
         ["Valencia County has the metro&rsquo;s Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup, but no hospital of its own: residents drive north to Presbyterian, UNM or Lovelace in Albuquerque for inpatient and specialty care. That makes the network question sharper than it looks. A plan sold in Valencia County is only as good as its Albuquerque hospitals.",
          "We compare what is sold at your ZIP code, confirm the Albuquerque providers you actually use are in-network, and set Advantage beside a Medigap policy, which covers all three systems without a network."],
         ["Presbyterian Hospital (Albuquerque)", "UNM Hospital (Albuquerque)", "Lovelace Medical Center (Albuquerque)", "Raymond G. Murphy VA Medical Center (Albuquerque)"],
         "Los Lunas, Belen, Bosque Farms, Peralta, Tom&eacute;, Los Chavez, Rio Communities, Isleta Pueblo",
         [("Which Medicare plans are available in Los Lunas?", "Valencia County typically offers a wide Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("There is no hospital in Valencia County. Does that change my plan choice?", "It makes the network question the whole question: whether the Albuquerque hospitals and doctors you use are in the plan&rsquo;s network. With Original Medicare and a Medigap policy there is no network to check. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["albuquerque", "rio-rancho", "kirtland-afb"]),
    city("santa-fe", "Santa Fe", "Santa Fe County", "santa-fe-north-central", "adobe",
         "Santa Fe&rsquo;s Medicare market is built around Christus St. Vincent, the largest hospital north of Albuquerque, with Presbyterian&rsquo;s Santa Fe campus as the second choice &mdash; and a menu that narrows for 2027.",
         ["Santa Fe County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Christus St. Vincent Regional Medical Center and Presbyterian Santa Fe Medical Center contract with different carriers, and Presbyterian Health Plan&rsquo;s exit from most Advantage plans for 2027 removes one of the local options. Albuquerque&rsquo;s specialists are an hour down I-25, which an Advantage network may or may not include.",
          "Santa Fe retirees travel more than most, and many keep a second place elsewhere, which is where a Medigap policy&rsquo;s any-provider access matters. We compare both paths with your doctors and your calendar."],
         ["Christus St. Vincent Regional Medical Center", "Presbyterian Santa Fe Medical Center", "UNM Health and Presbyterian (Albuquerque)", "VA New Mexico Health Care System community clinics"],
         "Santa Fe, Eldorado, Tesuque, Pojoaque, La Cienega, Edgewood, Cerrillos, Madrid, the Pueblos of the Pojoaque Valley",
         [("Which Medicare plans are available in Santa Fe?", "Santa Fe County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Are Christus St. Vincent and Presbyterian Santa Fe in the same plans?", "Rarely both in every plan. Each contracts with some Advantage carriers and not others; with Original Medicare and a Medigap policy there is no network to check. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["los-alamos", "taos", "albuquerque"]),
    city("roswell", "Roswell", "Chaves County", "southeast-permian", "plains",
         "Roswell has two hospitals, a moderate plan menu, and Lubbock three hours east for anything they cannot do.",
         ["Chaves County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Eastern New Mexico Medical Center, the region&rsquo;s Level III trauma center, and Lovelace Regional Hospital contract with different carriers, and patients drive in from Artesia, Dexter and the ranch country, so a plan&rsquo;s network has to reach the whole Pecos Valley.",
          "For a cardiac surgeon or a cancer center many Roswell families go to Lubbock or Albuquerque. We check whether a plan&rsquo;s network reaches there before you enroll, or steer you to a Medigap policy if you want no network at all."],
         ["Eastern New Mexico Medical Center", "Lovelace Regional Hospital", "VA New Mexico Health Care System community clinics"],
         "Roswell, Dexter, Hagerman, Lake Arthur, Artesia-area families, Fort Sumner",
         [("Which Medicare plans are available in Roswell?", "Chaves County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Eastern New Mexico Medical Center in my plan&rsquo;s network?", "ENMMC and Lovelace Regional contract with different Advantage plans, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["artesia", "carlsbad", "hobbs", "ruidoso"]),
    city("farmington", "Farmington", "San Juan County", "northwest-four-corners", "shiprock",
         "Farmington&rsquo;s San Juan Regional Medical Center serves the whole Four Corners, and Farmington families look north to Durango and Denver as often as south to Albuquerque.",
         ["San Juan County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. San Juan Regional Medical Center, a 198-bed Level III trauma center, is the region&rsquo;s hospital, and because patients come from Shiprock, Aztec, Bloomfield and the Navajo Nation chapters, a plan&rsquo;s network has to reach the whole basin. Many families see specialists in Durango, Colorado, or Denver, which a Medigap policy covers and an Advantage network may not.",
          "A large share of the county&rsquo;s Medicare beneficiaries are members of the Navajo Nation whose primary care runs through IHS facilities. Medicare pays those facilities, IHS encourages enrollment, and whether an Advantage plan lists your IHS hospital in its network is the first question to ask; our <a href=\"/rural-new-mexico\">rural New Mexico guide</a> has the details."],
         ["San Juan Regional Medical Center", "IHS and Navajo Nation facilities (Shiprock area)", "VA New Mexico Health Care System community clinics", "Durango and Denver hospitals (Colorado referrals)"],
         "Farmington, Aztec, Bloomfield, Kirtland, Shiprock, Flora Vista, Navajo Dam, the Navajo Nation chapters of San Juan County",
         [("Which Medicare plans are available in Farmington?", "San Juan County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I see a doctor in Durango or Denver with a New Mexico plan?", "With Original Medicare and a Medigap policy, yes. With a Medicare Advantage plan, only if the Colorado provider is in that plan&rsquo;s network or the plan covers out-of-network care. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["gallup", "albuquerque", "rio-rancho"]),
    city("clovis", "Clovis", "Curry County", "east-clovis-portales", "plains",
         "Clovis and Portales have Plains Regional Medical Center, Roosevelt General, the Cannon AFB retiree community, and Lubbock and Amarillo ninety minutes east for specialty care.",
         ["Curry County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Plains Regional Medical Center in Clovis belongs to Presbyterian, whose health plan is leaving most of the Advantage market for 2027, so the local lineup is being redrawn this fall. Roosevelt General Hospital in Portales serves the county to the south, and for anything beyond them the road runs east into Texas.",
          "Cannon Air Force Base adds a large TRICARE For Life community, for whom the Medicare decision is mostly Part B timing and whether an MA-only plan&rsquo;s extras are worth it. Our <a href=\"/cannon-afb\">Cannon AFB page</a> walks through it."],
         ["Plains Regional Medical Center (Presbyterian)", "Roosevelt General Hospital (Portales)", "Cannon AFB 27th Special Operations Medical Group (TRICARE)", "Lubbock and Amarillo hospitals (Texas referrals)"],
         "Clovis, Portales, Texico, Melrose, Fort Sumner, Grady, Cannon AFB housing areas",
         [("Which Medicare plans are available in Clovis?", "Curry County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year. Presbyterian&rsquo;s exit for 2027 changes the lineup this fall."),
          ("Can I use Lubbock specialists with a Clovis plan?", "With Original Medicare and a Medigap policy, yes. With an Advantage plan, only if the Texas provider is in that plan&rsquo;s network or the plan covers out-of-network care. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["cannon-afb", "roswell", "hobbs"]),
    city("hobbs", "Hobbs", "Lea County", "southeast-permian", "plains",
         "Hobbs and Lovington sit in the heart of the Permian, with Lea Regional and Nor-Lea as the two hospitals, royalty income that complicates IRMAA, and Midland and Lubbock as the referral cities.",
         ["Lea County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Lea Regional Medical Center in Hobbs and Nor-Lea General Hospital in Lovington, a 25-bed community hospital, contract with different carriers, and many families see specialists across the line in Midland or Lubbock, which a Medigap policy covers and an Advantage network may not.",
          "The Permian&rsquo;s royalty economy adds an income wrinkle: IRMAA is a cliff, and a strong year of oil-and-gas income in 2024 can raise your 2026 Medicare premium. Our <a href=\"/medicare-costs\">costs page</a> has the chart and the form to appeal when income drops."],
         ["Lea Regional Medical Center", "Nor-Lea General Hospital (Lovington)", "Midland and Lubbock hospitals (Texas referrals)"],
         "Hobbs, Lovington, Eunice, Jal, Tatum, Monument",
         [("Which Medicare plans are available in Hobbs?", "Lea County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I use Midland or Lubbock doctors with a Hobbs plan?", "With Original Medicare and a Medigap policy, yes. With an Advantage plan, only if the Texas provider is in that plan&rsquo;s network or the plan covers out-of-network care. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["carlsbad", "artesia", "roswell", "clovis"]),
    city("alamogordo", "Alamogordo", "Otero County", "central-mountains", "whitesands",
         "Alamogordo is Holloman country: Gerald Champion Regional Medical Center has been shared by the base and the town since 1999, and TRICARE For Life shapes more Medicare decisions here than anywhere else in the state.",
         ["Otero County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Gerald Champion Regional Medical Center, a 99-bed hospital that became the first in the country shared by active-duty military and civilians, is the basin&rsquo;s hospital; CHRISTUS Health&rsquo;s acquisition of it took effect July 1, 2026, and its Advantage contracts are worth re-checking this fall. Las Cruces and El Paso are the referral cities.",
          "Holloman&rsquo;s retirees reach 65 with TRICARE For Life, which usually makes a Medigap policy and a Part D plan unnecessary; our <a href=\"/holloman-afb\">Holloman AFB page</a> walks through it. The Mescalero Apache reservation to the northeast is served by an IHS facility, and our <a href=\"/rural-new-mexico\">rural New Mexico guide</a> covers how Medicare fits with it."],
         ["Gerald Champion Regional Medical Center (CHRISTUS)", "Holloman AFB 49th Medical Group (TRICARE)", "Las Cruces and El Paso hospitals (referrals)"],
         "Alamogordo, Tularosa, La Luz, Cloudcroft, High Rolls, Holloman AFB housing areas, Mescalero",
         [("Which Medicare plans are available in Alamogordo?", "Otero County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I have TRICARE For Life from Holloman. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit. See our Holloman AFB page."),
          ("How much does your help cost?", COST)],
         ["holloman-afb", "ruidoso", "las-cruces"]),
    city("las-cruces", "Las Cruces", "Do&ntilde;a Ana County", "las-cruces-southwest", "organ",
         "New Mexico&rsquo;s second Medicare market has three hospitals that contract differently, a White Sands Missile Range retiree community, and El Paso forty minutes down I-10 &mdash; which is where the network question gets interesting.",
         ["Do&ntilde;a Ana County offers a deep Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. MountainView Regional Medical Center (168 beds), Memorial Medical Center and the newer Three Crosses Regional Hospital each sign their own Advantage contracts, and a large share of the region&rsquo;s specialty care happens in El Paso, Texas, which a New Mexico plan&rsquo;s network may or may not include. A Medigap policy has no state line.",
          "White Sands Missile Range retirees carry TRICARE For Life, which changes the calculation entirely; Fort Bliss and the El Paso VA are just across the line. Our Texas section covers <a href=\"https://www.ecosinsurancesolutions.com/texas/el-paso\">El Paso</a> and <a href=\"https://www.ecosinsurancesolutions.com/texas/fort-bliss\">Fort Bliss</a> from the other side."],
         ["MountainView Regional Medical Center", "Memorial Medical Center", "Three Crosses Regional Hospital", "El Paso hospitals (Texas referrals)", "VA New Mexico Health Care System community clinics"],
         "Las Cruces, Mesilla, Do&ntilde;a Ana, Sunland Park, Anthony, Chaparral, Hatch, White Sands Missile Range families",
         [("Which Medicare plans are available in Las Cruces?", "Do&ntilde;a Ana County typically offers a deep Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I see a doctor in El Paso with a Las Cruces plan?", "With Original Medicare and a Medigap policy, yes. With a Medicare Advantage plan, only if the El Paso provider is in that plan&rsquo;s network or the plan covers out-of-network care, which we confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["deming", "silver-city", "alamogordo"]),
    city("carlsbad", "Carlsbad", "Eddy County", "southeast-permian", "plains",
         "Carlsbad has a community hospital, a Permian royalty economy, and Lubbock, Midland or Albuquerque a long drive away for specialty care.",
         ["Eddy County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Carlsbad Medical Center is the city&rsquo;s hospital, Artesia General serves the north end of the county, and for a specialist many families drive to Lubbock, Midland or Albuquerque, which a Medigap policy covers and an Advantage network may not.",
          "Royalty and mineral income makes IRMAA a local issue: a good year in 2024 shows up in your 2026 Part B premium. Our <a href=\"/medicare-costs\">costs page</a> has the chart."],
         ["Carlsbad Medical Center", "Artesia General Hospital", "Lubbock and Midland hospitals (Texas referrals)"],
         "Carlsbad, Loving, Malaga, White&rsquo;s City, Artesia-area families",
         [("Which Medicare plans are available in Carlsbad?", "Eddy County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Carlsbad Medical Center in my plan&rsquo;s network?", "It depends on the plan and the year. We confirm your hospital and doctors are in-network before you enroll, or steer you to a Medigap policy if you want no network at all."),
          ("How much does your help cost?", COST)],
         ["artesia", "hobbs", "roswell"]),
    city("gallup", "Gallup", "McKinley County", "northwest-four-corners", "shiprock",
         "Gallup has two hospitals &mdash; Rehoboth McKinley and the IHS&rsquo;s Gallup Indian Medical Center &mdash; and the highest share of Medicare beneficiaries in the state whose care runs through the Indian Health Service.",
         ["McKinley County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Rehoboth McKinley Christian Health Care Services serves the city and the surrounding Navajo and Zuni communities, and Gallup Indian Medical Center, an IHS hospital, serves eligible tribal members; for specialty care the road runs to Albuquerque or Flagstaff.",
          "Medicare and the IHS fit together better than most people assume: IHS is not insurance, its referral program is the payer of last resort, and Medicare pays IHS and tribal facilities for covered care and for the referrals they cannot fund. Whether an Advantage plan lists your IHS hospital in its network is the first question we ask; our <a href=\"/rural-new-mexico\">rural New Mexico guide</a> has the federal sources."],
         ["Rehoboth McKinley Christian Health Care Services", "Gallup Indian Medical Center (IHS)", "VA New Mexico Health Care System community clinics", "UNM Hospital and Presbyterian (Albuquerque referrals)"],
         "Gallup, Zuni, Crownpoint, Thoreau, Grants, Milan, the Navajo Nation chapters of McKinley County",
         [("Which Medicare plans are available in Gallup?", "McKinley County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I get my care at Gallup Indian Medical Center. Do I need Medicare?", "The IHS says it is not health insurance and encourages eligible tribal members to enroll in Medicare; enrolling does not affect your IHS eligibility, it pays the facility for your care, and it covers care the facility cannot provide. Enroll in Part B on time, because the late penalty lasts for life."),
          ("How much does your help cost?", COST)],
         ["farmington", "albuquerque", "rio-rancho"]),
    city("deming", "Deming", "Luna County", "las-cruces-southwest", "organ",
         "Deming has a 25-bed Critical Access Hospital, a winter population from colder states, and Las Cruces or El Paso an hour away for anything more.",
         ["Luna County offers a short Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Mimbres Valley Medical Center (until recently Mimbres Memorial Hospital) is a designated Critical Access Hospital, and for specialty care Deming families drive to Las Cruces or El Paso, which a Medigap policy covers and an Advantage network may not.",
          "Deming also fills each winter with retirees from colder states whose plans from home may cover only emergencies here; our agency is licensed in most of the states they come from, so we can compare from either side."],
         ["Mimbres Valley Medical Center", "MountainView Regional and Memorial Medical Center (Las Cruces)", "El Paso hospitals (Texas referrals)"],
         "Deming, Columbus, Lordsburg, Hidalgo County families, winter visitors",
         [("Which Medicare plans are available in Deming?", "Luna County typically offers a short Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I live an hour from a specialist. Which plan makes sense?", FAR),
          ("How much does your help cost?", COST)],
         ["las-cruces", "silver-city"]),
    city("los-lunas-placeholder", "", "", "", "", "", [], [], "", [], []),  # removed below
    city("los-alamos", "Los Alamos", "Los Alamos County", "santa-fe-north-central", "adobe",
         "Los Alamos has its own 47-bed hospital, a large population of lab retirees with federal or contractor retiree coverage, and Santa Fe and Albuquerque down the hill for specialty care.",
         ["Los Alamos County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Los Alamos Medical Center, the county&rsquo;s only hospital, handles emergency, surgical and inpatient care; Christus St. Vincent in Santa Fe and the Albuquerque systems handle the rest, which an Advantage network may or may not include.",
          "The lab&rsquo;s retirees are the local wrinkle: many reach 65 with a federal or contractor retiree plan, which changes whether to take Part B and whether a Medigap policy adds anything. A lump-sum payout in 2024 can also push you into an IRMAA tier for 2026. We compare with your retiree plan&rsquo;s paperwork in hand."],
         ["Los Alamos Medical Center", "Christus St. Vincent Regional Medical Center (Santa Fe)", "UNM Health and Presbyterian (Albuquerque referrals)"],
         "Los Alamos, White Rock, Pojoaque Valley, Espa&ntilde;ola-area families",
         [("Which Medicare plans are available in Los Alamos?", "Los Alamos County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I have a lab retiree health plan. Do I still need Part B?", "Usually, yes &mdash; most retiree plans pay secondary to Medicare once you are eligible and expect you to enroll in Part B, and the late penalty is permanent. Bring the plan&rsquo;s Medicare coordination pages and we will confirm before you decide."),
          ("How much does your help cost?", COST)],
         ["santa-fe", "taos", "albuquerque"]),
    city("silver-city", "Silver City", "Grant County", "las-cruces-southwest", "pinon",
         "Silver City has a 25-bed Critical Access Hospital, a retiree community drawn by the Gila, and Las Cruces, El Paso or Tucson two to three hours away for specialty care.",
         ["Grant County offers a short Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Gila Regional Medical Center is a 25-bed Critical Access Hospital, and for a cardiologist, an oncologist or a surgeon Silver City families drive to Las Cruces, El Paso or Tucson, which a Medigap policy covers and an Advantage network may not.",
          "Silver City draws retirees from Arizona, Texas and farther afield, many of whom keep a second place elsewhere. Your plan follows your permanent residence; our agency is licensed in Arizona and Texas as well, so we can compare from either side."],
         ["Gila Regional Medical Center", "Las Cruces and El Paso hospitals (referrals)", "Tucson hospitals (Arizona referrals)", "VA New Mexico Health Care System community clinics"],
         "Silver City, Bayard, Hurley, Santa Clara, Pinos Altos, Mimbres, Cliff, Glenwood, Reserve",
         [("Which Medicare plans are available in Silver City?", "Grant County typically offers a short Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I live two hours from a specialist. Which plan makes sense?", FAR),
          ("How much does your help cost?", COST)],
         ["deming", "las-cruces"]),
    city("taos", "Taos", "Taos County", "santa-fe-north-central", "pinon",
         "Taos has a 25-bed Critical Access Hospital, a second-home population from Texas and beyond, and Santa Fe or Albuquerque an hour and a half to three hours away for specialty care.",
         ["Taos County offers a short Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Holy Cross Medical Center is a 25-bed Critical Access Hospital, and for anything beyond it the road runs south to Santa Fe or Albuquerque, which a Medigap policy covers and an Advantage network may not. The villages of the high country &mdash; Questa, Red River, Pe&ntilde;asco &mdash; are farther still.",
          "Taos also has a large second-home population, and Taos Pueblo&rsquo;s members are served by IHS facilities; our <a href=\"/rural-new-mexico\">rural New Mexico guide</a> covers both the distance question and how Medicare fits with the IHS."],
         ["Holy Cross Medical Center", "Christus St. Vincent Regional Medical Center (Santa Fe)", "UNM Health and Presbyterian (Albuquerque referrals)", "VA New Mexico Health Care System community clinics"],
         "Taos, Ranchos de Taos, El Prado, Arroyo Seco, Questa, Red River, Angel Fire, Pe&ntilde;asco, Taos Pueblo",
         [("Which Medicare plans are available in Taos?", "Taos County typically offers a short Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I keep a place in Taos but live in Texas. Which plan covers both?", "Your plan is tied to your permanent residence. A Medigap policy with Original Medicare works in both states; most Advantage HMOs cover only emergencies outside their service area. Our agency is licensed in New Mexico and Texas, so we can compare from either side."),
          ("How much does your help cost?", COST)],
         ["santa-fe", "los-alamos"]),
    city("ruidoso", "Ruidoso", "Lincoln County", "central-mountains", "pinon",
         "Ruidoso is second-home country &mdash; a mountain town that fills with Texas retirees &mdash; with Lincoln County Medical Center in town and Alamogordo, Roswell, Las Cruces or El Paso for anything more.",
         ["Lincoln County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Lincoln County Medical Center in Ruidoso is the county&rsquo;s hospital; Gerald Champion in Alamogordo and the Roswell hospitals are the next stops, and El Paso or Lubbock the specialty cities, which a Medigap policy covers and an Advantage network may not.",
          "Many Ruidoso residents chose their plan in Lubbock, Midland or Dallas and moved their residence later, which opens a Special Enrollment Period and means choosing from the plans sold in Lincoln County. The 2024 South Fork and Salt fires displaced thousands here; Medicare gives a Special Enrollment Period to anyone a declared disaster kept from enrolling on time."],
         ["Lincoln County Medical Center", "Gerald Champion Regional Medical Center (Alamogordo)", "Eastern New Mexico Medical Center (Roswell)", "El Paso and Lubbock hospitals (Texas referrals)"],
         "Ruidoso, Ruidoso Downs, Alto, Capitan, Carrizozo, Mescalero, Cloudcroft-area families",
         [("Which Medicare plans are available in Ruidoso?", "Lincoln County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I moved to Ruidoso from Texas. Do I have to change my plan?", "If you changed your permanent residence, your old Advantage or Part D plan ends and you get a Special Enrollment Period to choose from the plans sold in Lincoln County. A Medigap policy stays in force wherever you live, though the premium may be re-rated. We help you move it cleanly."),
          ("How much does your help cost?", COST)],
         ["alamogordo", "roswell", "holloman-afb"]),
    city("artesia", "Artesia", "Eddy County", "southeast-permian", "plains",
         "Artesia has its own community hospital serving the Pecos Valley between Roswell and Carlsbad, a refinery-and-royalty economy, and Lubbock a long drive east for specialty care.",
         ["Eddy County offers a moderate Advantage menu, every Medigap carrier in New Mexico and the full Part D lineup. Artesia General Hospital provides 24-hour emergency, primary and specialty care in Artesia and runs clinics in Carlsbad; Roswell&rsquo;s hospitals are forty minutes north, and Lubbock, Midland or Albuquerque are the cities for anything they cannot do.",
          "Royalty and refinery income makes IRMAA a local issue, and Artesia&rsquo;s retirees are often the ones with the land. Our <a href=\"/medicare-costs\">costs page</a> has the chart and the appeal form."],
         ["Artesia General Hospital", "Eastern New Mexico Medical Center (Roswell)", "Carlsbad Medical Center", "Lubbock and Midland hospitals (Texas referrals)"],
         "Artesia, Hope, Loco Hills, Lake Arthur, Carlsbad-area families",
         [("Which Medicare plans are available in Artesia?", "Eddy County typically offers a moderate Medicare Advantage menu, every Medigap carrier in New Mexico, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Artesia General in my plan&rsquo;s network?", "It depends on the plan and the year. We confirm your hospital and doctors are in-network before you enroll, or steer you to a Medigap policy if you want no network at all."),
          ("How much does your help cost?", COST)],
         ["roswell", "carlsbad", "hobbs"]),
]
CITIES = [c for c in CITIES if c["slug"] != "los-lunas-placeholder"]

BASES = [
    dict(slug="kirtland-afb", name="Kirtland AFB (Albuquerque)", region="albuquerque-metro", scene="sandia",
         title="Medicare Near Kirtland AFB &amp; Albuquerque, NM | ECOS Medicare Solutions",
         desc="Medicare for military retirees and veterans around Kirtland Air Force Base and Albuquerque: TRICARE For Life, the 377th Medical Group, the Raymond G. Murphy VA next door, and which plans fit. From a retired Air Force officer.",
         h1="Medicare near Kirtland Air Force Base and Albuquerque",
         sub="Kirtland&rsquo;s retirees have TRICARE For Life, a base clinic that shares a campus with the Raymond G. Murphy VA Medical Center, and Albuquerque&rsquo;s three hospital systems a few miles away. Here is how it fits with Medicare &mdash; from a retired Air Force officer.",
         h2="Why the Medicare choice is different for a Kirtland family",
         intro=["Bernalillo County holds one of the largest military-retiree communities in the Southwest, and most of them reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left to decide is whether an MA-only Advantage plan adds dental, vision or hearing worth having &mdash; without duplicating the drug coverage you already have &mdash; and, this year, whether the plan you pick will still be sold in 2027, since Presbyterian is leaving most of that market.",
                "Veterans without TRICARE use the Raymond G. Murphy VA Medical Center on San Pedro, and here the Part B timing question is the one that matters: VA care is not creditable for Part B, so delaying Part B because you have the VA triggers a lifelong penalty. The 377th Medical Group is an outpatient clinic that sees retirees on a space-available basis; it is not a substitute for Medicare."],
         systems=["377th Medical Group, Kirtland AFB (TRICARE clinic)", "Raymond G. Murphy VA Medical Center", "Presbyterian Hospital", "UNM Hospital", "Lovelace Medical Center"],
         communities="Southeast Heights, Four Hills, Nob Hill, the East Mountains, Tijeras, Rio Rancho, Los Lunas, Belen",
         faqs=[("I retired from the Air Force with TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit; we check whether one is worth it for you, and whether it will still be sold in 2027."),
               ("I use the Albuquerque VA. Do I still need Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying it can trigger a permanent penalty and leaves you without coverage at a non-VA hospital. Enroll on time."),
               ("Can I keep using the Kirtland clinic after 65?", "Retirees can be seen at the 377th Medical Group on a space-available basis under TRICARE rules; Medicare does not pay there, and it is a clinic, not a hospital. Most Kirtland retirees pair TFL with civilian care at Presbyterian, UNM or Lovelace.")],
         nearby=["albuquerque", "rio-rancho", "los-lunas"], cta="Retired from Kirtland? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="holloman-afb", name="Holloman AFB (Alamogordo)", region="central-mountains", scene="whitesands",
         title="Medicare Near Holloman AFB &amp; Alamogordo, NM | ECOS Medicare Solutions",
         desc="Medicare for military retirees around Holloman Air Force Base and Alamogordo: TRICARE For Life, the 49th Medical Group, Gerald Champion Regional Medical Center, the VA, and which plans fit. From a retired Air Force officer.",
         h1="Medicare near Holloman Air Force Base and Alamogordo",
         sub="Holloman retirees have TRICARE For Life, a base clinic, and a civilian hospital &mdash; Gerald Champion &mdash; that has been shared with the base since 1999. Here is how it fits with Medicare.",
         h2="Why the Medicare choice is different for a Holloman family",
         intro=["Otero County&rsquo;s retiree community reaches 65 with TRICARE For Life, which requires Medicare Parts A and B, pays secondary to Medicare and carries creditable pharmacy coverage. A Medigap policy and a Part D plan are usually redundant for a TFL family; the open question is whether an MA-only Advantage plan&rsquo;s extras are worth it, and whether its network reaches Gerald Champion and the Las Cruces or El Paso specialists Alamogordo families use.",
                "Gerald Champion Regional Medical Center, a 99-bed hospital, was the first in the country shared by active-duty military and civilians; CHRISTUS Health&rsquo;s acquisition of it took effect July 1, 2026. The 49th Medical Group is an outpatient clinic that sees retirees on a space-available basis; Medicare does not pay there. Veterans without TFL use the VA&rsquo;s community clinic and Albuquerque or El Paso for specialty care, and for them the Part B timing rule is the one that matters."],
         systems=["49th Medical Group, Holloman AFB (TRICARE clinic)", "Gerald Champion Regional Medical Center (CHRISTUS)", "Las Cruces and El Paso hospitals (referrals)", "VA New Mexico Health Care System community clinics"],
         communities="Alamogordo, Tularosa, La Luz, Cloudcroft, Holloman AFB housing areas, Mescalero",
         faqs=[("I retired from Holloman with TRICARE For Life. Do I need anything besides Medicare A and B?", "Usually not. TFL fills Medicare&rsquo;s gaps and its pharmacy is creditable. An MA-only Advantage plan can add dental or vision; we check whether one is worth it and whether its network reaches your doctors."),
               ("Does Medicare pay at the Holloman clinic?", "No. The 49th Medical Group sees retirees on a space-available basis under TRICARE rules. Most Holloman retirees pair TFL with civilian care at Gerald Champion and, for specialists, Las Cruces or El Paso."),
               ("I use the VA and do not have TRICARE. Do I need Part B?", "In most cases, yes. VA care is not creditable for Part B; delaying it triggers a permanent penalty and leaves you uncovered at a non-VA hospital.")],
         nearby=["alamogordo", "ruidoso", "las-cruces"], cta="Retired from Holloman? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="cannon-afb", name="Cannon AFB (Clovis)", region="east-clovis-portales", scene="plains",
         title="Medicare Near Cannon AFB &amp; Clovis, NM | ECOS Medicare Solutions",
         desc="Medicare for military retirees around Cannon Air Force Base, Clovis and Portales: TRICARE For Life, the 27th Special Operations Medical Group, Plains Regional Medical Center, and which plans fit. From a retired Air Force officer.",
         h1="Medicare near Cannon Air Force Base, Clovis and Portales",
         sub="Cannon&rsquo;s retirees have TRICARE For Life, a base clinic, Presbyterian&rsquo;s Plains Regional Medical Center in Clovis, and Lubbock ninety minutes east. Here is how it fits with Medicare.",
         h2="Why the Medicare choice is different for a Cannon family",
         intro=["Curry County&rsquo;s retiree community reaches 65 with TRICARE For Life, which requires Medicare Parts A and B, pays secondary to Medicare and carries creditable pharmacy coverage. A Medigap policy and a Part D plan are usually redundant for a TFL family; the live question is whether an MA-only Advantage plan&rsquo;s dental, vision and hearing extras are worth having, and whether its network reaches Plains Regional in Clovis and the Lubbock or Amarillo specialists eastern New Mexico relies on.",
                "The 27th Special Operations Medical Group is an outpatient clinic that sees retirees on a space-available basis; Medicare does not pay there. Plains Regional Medical Center belongs to Presbyterian, whose health plan is leaving most of the Advantage market for 2027, so networks here are being redrawn this fall. Veterans without TFL use the VA&rsquo;s community clinics and Albuquerque or Amarillo for specialty care, and for them the Part B timing rule is the one that matters."],
         systems=["27th Special Operations Medical Group, Cannon AFB (TRICARE clinic)", "Plains Regional Medical Center (Presbyterian, Clovis)", "Roosevelt General Hospital (Portales)", "Lubbock and Amarillo hospitals (Texas referrals)"],
         communities="Clovis, Portales, Texico, Melrose, Cannon AFB housing areas, Farwell-area families across the Texas line",
         faqs=[("I retired from Cannon with TRICARE For Life. Which Medicare plan should I pick?", "For most TFL families, Original Medicare Parts A and B with TFL is complete coverage. An MA-only Advantage plan can add dental, vision and hearing without duplicating your pharmacy benefit; we check whether one is worth it for you and whether it will still be sold in 2027."),
               ("Does Medicare pay at the Cannon clinic?", "No. The 27th Special Operations Medical Group sees retirees on a space-available basis under TRICARE rules. Most Cannon retirees pair TFL with civilian care at Plains Regional or Roosevelt General and, for specialists, Lubbock or Amarillo."),
               ("Can I use Lubbock specialists with TRICARE For Life and Medicare?", "Yes. Original Medicare has no network and TFL follows it, so a Lubbock or Amarillo provider that accepts Medicare is covered the same as one in Clovis.")],
         nearby=["clovis", "roswell", "hobbs"], cta="Retired from Cannon? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
]
