"""Indiana regions, cities and military communities."""
COST = "Nothing. Independent agents are paid by the carriers when you enroll, so comparing plans and reviewing your coverage each year is free to you."
SWITCH = ("Use Indiana&rsquo;s Medigap birthday rule. If you are 65 or older and already have a Medigap policy, in the window that opens 31 days before your birthday and closes 31 days after it "
          "you can move to the same plan letter at another insurer without health questions. We compare every Indiana carrier&rsquo;s current premium and filed rate history before you switch.")
MOVED = ("Check it this fall. IU Health Plans&rsquo; Medicare Advantage members were moved under Anthem for 2026 after Elevance Health bought the plan, and nationally UnitedHealthcare and Humana withdrew from hundreds of counties. "
         "A plan that left you gives you a Special Enrollment Period and usually a guaranteed-issue right to Medigap; a plan that merely changed hands is something to re-check during the Annual Election Period.")

REGIONS = [
    dict(slug="central-indiana", name="Indianapolis Metro &amp; Central Indiana", short="Central Indiana", scene="monument",
         eyebrow="Medicare by region · Indianapolis, the doughnut counties, Kokomo &amp; Anderson",
         h1="Medicare help across Indianapolis and Central Indiana",
         sub="Marion, Hamilton, Hendricks, Johnson, Hancock and the counties around them &mdash; the deepest plan menu in Indiana, five big hospital systems, and a network question that starts with which one your doctor belongs to.",
         counties="Marion, Hamilton, Hendricks, Johnson, Hancock, Boone, Morgan, Shelby, Madison, Howard, Tipton, Clinton, Putnam",
         cities=["indianapolis", "carmel", "fishers", "noblesville", "greenwood", "kokomo", "anderson"],
         systems=["IU Health (Methodist, University, North, Saxony)", "Ascension St. Vincent (Indianapolis, Carmel, Anderson, Kokomo)", "Community Health Network (North, East, South, Howard)", "Franciscan Health (Indianapolis, Carmel)", "Eskenazi Health", "Riverview Health (Noblesville)", "Johnson Memorial Health (Franklin)", "Richard L. Roudebush VA Medical Center"],
         note="<p><strong>What changed for 2026:</strong> IU Health Plans, the Advantage plan built on the IU Health system that many central Indiana retirees chose for that reason, was bought by Elevance Health and its members received Anthem plans for 2026. If that was you, confirm your IU Health doctors and everyone else are in the new plan. Anthem, Humana, UnitedHealthcare, Aetna and Wellcare each contract with the five systems differently.</p>",
         intro=["More than a fifth of Indiana&rsquo;s Medicare beneficiaries live in the Indianapolis metro, and the plan menu shows it: dozens of Medicare Advantage plans in Marion and Hamilton counties, every Medigap carrier licensed in Indiana, and the full Part D lineup. The trade-off is that central Indiana&rsquo;s care is organized into large systems that contract separately &mdash; IU Health, Ascension St. Vincent, Community, Franciscan and Eskenazi &mdash; so a $0-premium plan that includes IU Health Methodist may exclude Community North, or the reverse.",
                "Outside the beltway the menu thins a little but the systems follow: Ascension St. Vincent and Community in Kokomo and Anderson, Riverview in Noblesville, Johnson Memorial in Franklin. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy &mdash; which, with Indiana&rsquo;s new birthday rule, you can now re-shop every year."],
         faqs=[("Which Medicare plans are available in Indianapolis?", "Marion County typically has the widest choice in Indiana: dozens of Medicare Advantage plans from Anthem, Humana, UnitedHealthcare, Aetna, Wellcare and others, every Medigap carrier in the state, and all standalone Part D plans. Availability is set by county and ZIP code and changes each plan year."),
               ("Are IU Health and Ascension St. Vincent in the same Advantage plans?", "Rarely both in every plan. Each system contracts with some carriers and not others, and the lists change each October. With Original Medicare and a Medigap policy there is no network to check. We confirm your doctors before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="northwest-indiana", name="Northwest Indiana &amp; the Region", short="the Region", scene="mill",
         eyebrow="Medicare by region · Gary, Hammond, Merrillville, Valparaiso &amp; Michigan City",
         h1="Medicare help across Northwest Indiana and the Region",
         sub="Lake, Porter and LaPorte counties and the farm counties south of them &mdash; steel-town retirees, three hospital systems that contract on their own terms, and a care map that runs straight into Chicago.",
         counties="Lake, Porter, LaPorte, Jasper, Newton, Starke, Pulaski",
         cities=["hammond", "gary"],
         systems=["Methodist Hospitals (Northlake in Gary, Southlake in Merrillville)", "Community Healthcare System (Community Hospital, Munster)", "Franciscan Health (Crown Point, Munster, Michigan City)", "Northwest Health (Porter in Valparaiso, La Porte, Starke)", "Chicago-area hospitals across the state line (network-dependent)"],
         note="<p><strong>Local wrinkle:</strong> a lot of Region residents see specialists in Chicago. With Original Medicare and a Medigap policy that is simply covered. With an Advantage plan it depends on whether the Illinois provider is in the network, which some Indiana plans include and most do not. Many Region retirees also carry a union or steel-company retiree plan, which needs its own look before you change anything.</p>",
         intro=["The Region has a deep Advantage menu in Lake and Porter counties and a care map divided among Methodist Hospitals, Community Healthcare System and Franciscan Health, each of which signs its own contracts. Franciscan&rsquo;s new Crown Point hospital and Community&rsquo;s Munster campus anchor the south suburbs; Methodist&rsquo;s Northlake campus serves Gary; and for anything the Region does not do, Chicago is forty minutes up the Skyway &mdash; if your plan reaches it.",
                "Retiree plans matter more here than almost anywhere in Indiana: steelworker and union trusts, railroad retirement, municipal plans. Whether to keep one, and what it becomes at 65, is usually the first question we answer for a Region family."],
         faqs=[("Which Medicare plans are available in Lake County?", "Lake County typically offers a wide Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup. Porter and LaPorte counties are similar; Jasper, Newton, Starke and Pulaski have fewer Advantage plans. We compare what is sold at your address."),
               ("Can I use a Chicago hospital with an Indiana plan?", "With Original Medicare and a Medigap policy, yes &mdash; any Illinois provider that accepts Medicare is covered. With a Medicare Advantage plan, only if that provider is in the plan&rsquo;s network, which we confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="north-central-indiana", name="South Bend, Elkhart &amp; North Central Indiana", short="North Central Indiana", scene="lakes",
         eyebrow="Medicare by region · South Bend, Mishawaka, Elkhart, Goshen, Warsaw &amp; Plymouth",
         h1="Medicare help across South Bend, Elkhart and North Central Indiana",
         sub="St. Joseph, Elkhart, Marshall and Kosciusko counties and the lake country around them &mdash; Beacon and Saint Joseph Health System splitting the metro, RV-industry retirees, and a border with Michigan that the hospitals themselves cross.",
         counties="St. Joseph, Elkhart, Marshall, Kosciusko, Fulton, Cass, Miami",
         cities=["south-bend", "mishawaka", "elkhart"],
         systems=["Beacon Health System (Memorial Hospital of South Bend, Elkhart General, Beacon Granger, Community Hospital of Bremen)", "Saint Joseph Health System (Mishawaka Medical Center, Plymouth Medical Center)", "Goshen Health", "VA Northern Indiana clinics"],
         note="<p><strong>Local plans to know:</strong> Beacon and Saint Joseph Health System are the two systems in the metro, and they contract with different Advantage carriers. Beacon also runs hospitals in southwestern Michigan, so a plan&rsquo;s network can matter on both sides of the line. Elkhart County&rsquo;s RV-industry retirees often arrive at 65 with employer coverage that needs a decision.</p>",
         intro=["North central Indiana&rsquo;s Medicare menu is moderate-to-deep in St. Joseph and Elkhart counties and thinner in the lake counties to the south. The network question is a two-system question: Beacon (Memorial in South Bend, Elkhart General) and Saint Joseph Health System (Mishawaka, Plymouth) each contract with some Advantage plans and not others, and Goshen Health stands on its own.",
                "Kosciusko and Marshall counties are lake-cottage country and Grissom Air Reserve Base sits at the region&rsquo;s southern edge in Miami County; many families here split time in Florida or Michigan, which is where a Medigap policy&rsquo;s any-provider access earns its premium."],
         faqs=[("Which Medicare plans are available in South Bend and Elkhart?", "St. Joseph and Elkhart counties typically offer a solid Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup. The lake counties to the south have fewer Advantage plans. We compare what is sold at your address."),
               ("Is Beacon or Saint Joseph in my plan&rsquo;s network?", "Each contracts with some Advantage plans and not others, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="northeast-indiana", name="Fort Wayne &amp; Northeast Indiana", short="Northeast Indiana", scene="courthouse",
         eyebrow="Medicare by region · Fort Wayne, Auburn, Angola, Huntington, Marion &amp; the lakes",
         h1="Medicare help across Fort Wayne and Northeast Indiana",
         sub="Allen County and the ten counties around it &mdash; Parkview and Lutheran, the two systems that decide almost every Advantage shortlist in the northeast, plus the VA&rsquo;s Fort Wayne and Marion campuses.",
         counties="Allen, DeKalb, Steuben, LaGrange, Noble, Whitley, Huntington, Wells, Adams, Wabash, Grant",
         cities=["fort-wayne"],
         systems=["Parkview Health (Parkview Regional Medical Center and community hospitals)", "Lutheran Health Network (Lutheran Hospital of Indiana, Dupont Hospital and others)", "VA Northern Indiana Health Care System (Fort Wayne and Marion campuses)"],
         note="<p><strong>Local plans to know:</strong> Northeast Indiana is a two-system market. Parkview and Lutheran each contract with different Advantage carriers, and a plan that is built around one may leave the other out entirely. If your cardiologist is at Parkview Regional and your surgeon at Lutheran, that decides the plan type before the premium does.</p>",
         intro=["Fort Wayne has a deep Advantage menu and one of the clearest network splits in the state: Parkview Health on one side, Lutheran Health Network on the other, each with a flagship hospital and a ring of community hospitals across the northeast counties. The counties around Allen lean on those two systems for anything beyond primary care, so a plan&rsquo;s network has to reach the whole region, not just the city.",
                "Northeast Indiana also has one of the state&rsquo;s larger veteran populations, served by the VA&rsquo;s Fort Wayne and Marion campuses; how VA care coordinates with Medicare is on our Veterans page. And the lake counties &mdash; Steuben, Noble, Kosciusko next door &mdash; send a lot of retirees south each winter."],
         faqs=[("Which Medicare plans are available in Fort Wayne?", "Allen County typically offers a wide Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup. The surrounding counties have fewer Advantage plans. We compare what is sold at your address."),
               ("Do I have to choose between Parkview and Lutheran?", "Not with Original Medicare and a Medigap policy &mdash; both accept Medicare, so both are covered with no network. With Medicare Advantage, often yes: each contracts with different carriers. We confirm your doctors before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="west-central-indiana", name="Lafayette, Terre Haute &amp; the Wabash Valley", short="the Wabash Valley", scene="coveredbridge",
         eyebrow="Medicare by region · Lafayette, West Lafayette, Terre Haute, Crawfordsville &amp; Parke County",
         h1="Medicare help across Lafayette, Terre Haute and the Wabash Valley",
         sub="Tippecanoe, Vigo and the river counties between them &mdash; IU Health Arnett and Franciscan in Lafayette, a moderate menu in Terre Haute, and long drives to specialty care in the covered-bridge counties.",
         counties="Tippecanoe, White, Carroll, Benton, Warren, Fountain, Montgomery, Vermillion, Parke, Vigo, Clay, Sullivan",
         cities=["lafayette", "terre-haute"],
         systems=["IU Health Arnett Hospital (Lafayette)", "Franciscan Health Lafayette East", "Terre Haute Regional Hospital", "VA clinics in Lafayette and Terre Haute (Roudebush VA)"],
         note="<p><strong>What to watch:</strong> Health Alliance, the Carle-owned Advantage plan sold in parts of the Wabash Valley, closed at the end of 2025. If you were on it and have not re-checked what you were moved to, the Annual Election Period is the time. Outside Tippecanoe and Vigo counties the Advantage menu is short and the drive to a specialist is long, which is where a Medigap policy earns its keep.</p>",
         intro=["Lafayette is a two-system town &mdash; IU Health Arnett and Franciscan Health &mdash; with Purdue&rsquo;s retirees and a solid Advantage menu; Terre Haute&rsquo;s menu is moderate and its hospitals contract differently again. The counties between and around them, from Parke County&rsquo;s covered bridges to the Illinois line, have thin menus and depend on Lafayette, Terre Haute or Indianapolis for anything beyond primary care.",
                "Because the Wabash Valley borders Illinois, some residents use Champaign or Danville providers; with an Advantage plan that is a network question, with a Medigap policy it is not."],
         faqs=[("Which Medicare plans are available in Lafayette?", "Tippecanoe County typically offers a solid Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup. Vigo County&rsquo;s menu is moderate; the rural river counties have fewer Advantage plans."),
               ("My Wabash Valley Advantage plan closed or changed. What now?", MOVED),
               ("How much does your help cost?", COST)]),
    dict(slug="east-central-indiana", name="Muncie, Richmond &amp; East Central Indiana", short="East Central Indiana", scene="farm",
         eyebrow="Medicare by region · Muncie, Richmond, New Castle, Portland &amp; the Ohio line",
         h1="Medicare help across Muncie, Richmond and East Central Indiana",
         sub="Delaware, Wayne, Henry and the farm counties along the Ohio line &mdash; IU Health Ball Memorial and Reid Health as the two anchors, a moderate menu, and a lot of retirees from the auto plants and glass works with a retiree plan to sort out.",
         counties="Delaware, Henry, Randolph, Jay, Blackford, Wayne, Fayette, Union, Rush",
         cities=["muncie"],
         systems=["IU Health Ball Memorial Hospital (Muncie)", "Reid Health (Richmond, serving seven counties)", "IU Health and Ascension St. Vincent specialists in Indianapolis"],
         note="<p><strong>What to watch:</strong> East central Indiana was IU Health Plans country, and those Advantage members were moved under Anthem for 2026 after Elevance Health bought the plan. Reid Health in Richmond reaches into Ohio, and some Wayne County residents use Dayton providers, which is a network question on an Advantage plan and not on a Medigap policy.</p>",
         intro=["East central Indiana is hospital-town country: Muncie&rsquo;s Ball Memorial (IU Health) and Richmond&rsquo;s Reid Health anchor the region, and the counties around them lean on those two for anything beyond primary care. Advantage menus are moderate in Delaware and Wayne counties and thin in the farm counties between, which is where Original Medicare with a Medigap policy &mdash; now with Indiana&rsquo;s birthday rule &mdash; is often the practical answer.",
                "The region&rsquo;s retirees are heavily industrial: auto, glass, wire. Many reach 65 with a union retiree plan whose value depends on what it becomes at 65; we set it beside the individual options before anyone cancels anything."],
         faqs=[("Which Medicare plans are available in Muncie?", "Delaware County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup. The rural counties around it have fewer Advantage plans."),
               ("I was on IU Health Plans. What happened?", MOVED),
               ("How much does your help cost?", COST)]),
    dict(slug="southwest-indiana", name="Evansville &amp; Southwest Indiana", short="Southwest Indiana", scene="river",
         eyebrow="Medicare by region · Evansville, Newburgh, Jasper, Vincennes &amp; the Pocket",
         h1="Medicare help across Evansville and Southwest Indiana",
         sub="Vanderburgh, Warrick, Dubois, Knox and the river counties &mdash; Deaconess and Ascension St. Vincent splitting Evansville, a care map that reaches into Kentucky and Illinois, and the Evansville VA for veterans.",
         counties="Vanderburgh, Warrick, Posey, Gibson, Pike, Dubois, Spencer, Perry, Knox, Daviess, Martin",
         cities=["evansville"],
         systems=["Deaconess Health System (Midtown, Gateway in Newburgh)", "Ascension St. Vincent Evansville", "Good Samaritan (Vincennes)", "Deaconess Memorial (Jasper)", "Evansville VA Health Care Center (Marion, Illinois VA)"],
         note="<p><strong>Local wrinkle:</strong> Evansville&rsquo;s systems serve a three-state region, and plenty of Pocket residents see doctors in Owensboro or Henderson, Kentucky. On an Advantage plan that is a network question; on a Medigap policy it is not. Naval Support Activity Crane, in Martin County, gives the region a small military-retiree community with TRICARE For Life.</p>",
         intro=["Southwest Indiana is a two-system market at its center &mdash; Deaconess and Ascension St. Vincent in Evansville, contracting with different Advantage carriers &mdash; and a one-hospital-per-county market everywhere else: Good Samaritan in Vincennes, Deaconess Memorial in Jasper, and the small hospitals along the river. Vanderburgh and Warrick counties have a moderate Advantage menu; the rural counties have fewer plans and longer drives.",
                "Veterans in the Pocket are served by the Evansville VA Health Care Center, part of the Marion, Illinois VA, with a clinic in Vincennes; how that coordinates with Medicare is on our Veterans page."],
         faqs=[("Which Medicare plans are available in Evansville?", "Vanderburgh and Warrick counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup. The rural counties around them have fewer Advantage plans."),
               ("Is Deaconess or Ascension St. Vincent in my plan&rsquo;s network?", "Each contracts with some Advantage plans and not others, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="south-central-indiana", name="Bloomington, Columbus &amp; South Central Indiana", short="South Central Indiana", scene="quarry",
         eyebrow="Medicare by region · Bloomington, Columbus, Seymour, Bedford &amp; Brown County",
         h1="Medicare help across Bloomington, Columbus and South Central Indiana",
         sub="Monroe, Bartholomew, Jackson, Lawrence and the hill counties &mdash; IU Health&rsquo;s new Bloomington hospital, Columbus Regional Health, university and Cummins retirees, and limestone-country distances to specialty care.",
         counties="Monroe, Brown, Bartholomew, Jackson, Lawrence, Orange, Washington, Greene, Owen",
         cities=["bloomington", "columbus"],
         systems=["IU Health Bloomington Hospital (Regional Academic Health Center)", "Monroe Hospital (Bloomington)", "Columbus Regional Health", "Schneck Medical Center (Seymour)", "Bloomington VA clinic (Roudebush VA)"],
         note="<p><strong>Local plans to know:</strong> Monroe County was IU Health Plans territory, and its Advantage members were moved under Anthem for 2026. Columbus Regional Health is independent and contracts on its own terms. Indianapolis specialists are an hour up I-65 or State Road 37, which an Advantage network may or may not include.</p>",
         intro=["South central Indiana&rsquo;s Medicare menu is moderate in Monroe and Bartholomew counties and thin in the hill counties around them. The care map is simpler than Indianapolis&rsquo;s but the distances are longer: IU Health Bloomington and Monroe Hospital in Bloomington, Columbus Regional in Columbus, Schneck in Seymour, and then a drive. A plan&rsquo;s network has to reach where you will actually be referred.",
                "Indiana University and Cummins retirees often arrive at 65 with a retiree plan in hand, which is the first thing we look at. Brown County and the lake towns also send a lot of retirees to Florida each winter; our snowbirds guide covers which plans travel."],
         faqs=[("Which Medicare plans are available in Bloomington?", "Monroe County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup. The hill counties around it have fewer Advantage plans."),
               ("I was on IU Health Plans in Bloomington. What happened?", MOVED),
               ("How much does your help cost?", COST)]),
    dict(slug="southeast-indiana", name="Southeast Indiana &amp; the Ohio River towns", short="Southeast Indiana", scene="river",
         eyebrow="Medicare by region · Jeffersonville, New Albany, Madison, Lawrenceburg &amp; the river counties",
         h1="Medicare help across Southeast Indiana and the Ohio River towns",
         sub="Clark, Floyd, Dearborn, Jefferson and the river counties &mdash; where the nearest big hospital is often in Louisville or Cincinnati, and whether your plan reaches across the river is the whole question.",
         counties="Clark, Floyd, Harrison, Crawford, Scott, Jefferson, Switzerland, Ohio, Dearborn, Ripley, Franklin, Decatur, Jennings",
         cities=["jeffersonville-new-albany"],
         systems=["Clark Memorial Health (Jeffersonville; Norton Healthcare and LifePoint Health)", "Baptist Health Floyd (New Albany)", "Norton King&rsquo;s Daughters&rsquo; Health (Madison)", "Margaret Mary Health (Batesville)", "Highpoint Health (Lawrenceburg)", "Louisville and Cincinnati hospitals across the river (network-dependent)"],
         note="<p><strong>Local wrinkle:</strong> Southeast Indiana&rsquo;s own hospitals are increasingly run by Kentucky systems &mdash; Norton in Jeffersonville and Madison, Baptist Health in New Albany &mdash; and the specialists are across the bridge. Some Indiana Advantage plans include Louisville or Cincinnati providers; most do not. With Original Medicare and a Medigap policy there is no line to worry about.</p>",
         intro=["Southeast Indiana is a border market. Clark and Floyd counties are part of metro Louisville and their hospitals are run by Louisville systems; Dearborn and Ohio counties look to Cincinnati; the river towns between lean on one hospital apiece and a long drive. The Advantage menu is moderate in Clark and Floyd and thin elsewhere, and its usefulness depends entirely on whether the network crosses the river.",
                "That is why so many families here keep Original Medicare with a Medigap policy: it covers Norton, Baptist Health, UofL Health and the Cincinnati systems alike, with no network to check &mdash; and with Indiana&rsquo;s birthday rule, the premium can now be shopped every year."],
         faqs=[("Which Medicare plans are available in Jeffersonville and New Albany?", "Clark and Floyd counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup. The river counties east of them have fewer Advantage plans."),
               ("Can I use a Louisville or Cincinnati hospital with an Indiana plan?", "With Original Medicare and a Medigap policy, yes &mdash; any Kentucky or Ohio provider that accepts Medicare is covered. With a Medicare Advantage plan, only if that provider is in the plan&rsquo;s network, which we confirm before you enroll."),
               ("How much does your help cost?", COST)]),
]

def city(slug, name, county, region, scene, sub, intro, systems, communities, faqs, nearby):
    return dict(slug=slug, name=name, county=county, region=region, scene=scene, sub=sub, intro=intro, systems=systems, communities=communities, faqs=faqs, nearby=nearby)

CITIES = [
    city("indianapolis", "Indianapolis", "Marion County", "central-indiana", "speedway",
         "From Broad Ripple to Beech Grove, Indianapolis has the deepest Medicare menu in Indiana &mdash; and the most ways to pick a plan that leaves your doctor out. The comparison here starts with your hospital system.",
         ["Marion County offers dozens of Medicare Advantage plans, every Medigap carrier licensed in Indiana and the full Part D lineup. The catch is that Indianapolis care is organized into large systems that contract separately: IU Health (Methodist and University downtown), Ascension St. Vincent on 86th Street, Community Health Network (North, East, South), Franciscan Health on the south side, and Eskenazi Health, the county hospital. A plan that includes IU Health may exclude Community, or the reverse, and the lists change every October.",
          "For 2026 there was an extra wrinkle: IU Health Plans, the Advantage plan built on the IU Health system, was bought by Elevance Health and its members received Anthem plans. We compare what is actually offered at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy so you can see the trade-off plainly."],
         ["IU Health Methodist and University hospitals", "Ascension St. Vincent Indianapolis", "Community Health Network (North, East, South)", "Franciscan Health Indianapolis", "Eskenazi Health", "Richard L. Roudebush VA Medical Center"],
         "Broad Ripple, Meridian-Kessler, Irvington, Fountain Square, Beech Grove, Lawrence, Speedway, Southport, Castleton, Nora, Pike Township, Warren Township, Franklin Township",
         [("Which Medicare plans are available in Indianapolis?", "Marion County typically has the widest choice in Indiana: dozens of Medicare Advantage plans, every Medigap carrier in the state, and all standalone Part D plans. Availability is set by ZIP code and changes each plan year; we compare what is offered at your address."),
          ("Will my IU Health or Community doctors take a Medicare Advantage plan?", "It depends on the specific plan&rsquo;s network, and the contracts change every year. Before you enroll we confirm your providers at IU Health, Ascension St. Vincent, Community, Franciscan or Eskenazi are in-network and your prescriptions are on the formulary, so there are no surprises in January."),
          ("How much does your help cost?", COST)],
         ["carmel", "greenwood", "fishers", "anderson"]),
    city("fort-wayne", "Fort Wayne", "Allen County", "northeast-indiana", "courthouse",
         "Indiana&rsquo;s second city is a two-system market &mdash; Parkview or Lutheran &mdash; and that split decides most Advantage shortlists before the premium does.",
         ["Allen County offers a wide Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Parkview Health, anchored by Parkview Regional Medical Center on the north side, and Lutheran Health Network, anchored by Lutheran Hospital of Indiana on the southwest side with Dupont Hospital in the north, each contract with different carriers. Because patients drive in from Auburn, Columbia City, Huntington and Decatur, a plan&rsquo;s network has to reach the whole northeast.",
          "Fort Wayne also has one of the state&rsquo;s larger veteran communities, served by the VA Northern Indiana Health Care System&rsquo;s Fort Wayne campus; the Part B timing question for VA users is on our Veterans page. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Parkview Regional Medical Center", "Lutheran Hospital of Indiana", "Dupont Hospital (Lutheran Health Network)", "VA Northern Indiana Health Care System, Fort Wayne campus"],
         "Aboite, Southwest Fort Wayne, Northeast Fort Wayne, Dupont, New Haven, Leo-Cedarville, Huntertown, Auburn, Columbia City, Huntington, Decatur, Angola-area lake families",
         [("Which Medicare plans are available in Fort Wayne?", "Allen County typically offers a wide Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Parkview or Lutheran in my plan&rsquo;s network?", "Each contracts with some Advantage plans and not others, changing year to year, and a plan built around one may leave the other out. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["elkhart", "kokomo", "muncie"]),
    city("evansville", "Evansville", "Vanderburgh County", "southwest-indiana", "river",
         "The Pocket&rsquo;s hub has two hospital systems, a VA health care center, and a care map that reaches into Kentucky and Illinois &mdash; three different Medicare questions in one county.",
         ["Vanderburgh and Warrick counties offer a moderate Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Deaconess (Midtown in Evansville, Gateway in Newburgh) and Ascension St. Vincent Evansville contract with different carriers, and because Evansville&rsquo;s systems serve a three-state region, plenty of residents also see doctors in Owensboro or Henderson, Kentucky, which an Advantage network may or may not include.",
          "Veterans here are served by the Evansville VA Health Care Center, part of the Marion, Illinois VA; how it coordinates with Medicare is on our Veterans page. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Deaconess Midtown Hospital", "Deaconess Gateway Hospital (Newburgh)", "Ascension St. Vincent Evansville", "Evansville VA Health Care Center"],
         "Evansville, Newburgh, Boonville, Mount Vernon, Princeton, Haubstadt, Chandler, Darmstadt, Henderson-area and Owensboro-area families",
         [("Which Medicare plans are available in Evansville?", "Vanderburgh and Warrick counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I see a doctor in Kentucky with an Evansville plan?", "With Original Medicare and a Medigap policy, yes. With a Medicare Advantage plan, only if the Kentucky provider is in that plan&rsquo;s network, which we confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["bloomington", "jeffersonville-new-albany", "terre-haute"]),
    city("south-bend", "South Bend", "St. Joseph County", "north-central-indiana", "lakes",
         "South Bend&rsquo;s Medicare menu is split between Beacon and Saint Joseph Health System, and its care map runs across the Michigan line &mdash; which is why the network question comes first here.",
         ["St. Joseph County offers a solid Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Beacon Health System (Memorial Hospital of South Bend, Beacon Granger) and Saint Joseph Health System (Mishawaka Medical Center) contract with different carriers, and Beacon also runs hospitals in southwestern Michigan, so a plan&rsquo;s network can matter on both sides of the line.",
          "Notre Dame and university retirees, and the RV-industry retirees just east in Elkhart County, often arrive at 65 with employer coverage that needs a decision before anything else. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Memorial Hospital of South Bend (Beacon)", "Beacon Granger Hospital", "Saint Joseph Health System Mishawaka Medical Center", "VA Northern Indiana clinics"],
         "South Bend, Granger, Roseland, Notre Dame, Osceola, New Carlisle, North Liberty, Lakeville, Niles-area and Michigan-line families",
         [("Which Medicare plans are available in South Bend?", "St. Joseph County typically offers a solid Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Beacon Memorial in my plan&rsquo;s network?", "Beacon and Saint Joseph Health System contract with different Advantage plans, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["mishawaka", "elkhart", "gary"]),
    city("carmel", "Carmel", "Hamilton County", "central-indiana", "monument",
         "Carmel and Zionsville have three hospitals within a few miles of each other &mdash; IU Health North, Ascension St. Vincent Carmel and Franciscan Health Carmel &mdash; and each contracts on its own terms.",
         ["Hamilton County has the Indianapolis metro&rsquo;s deep Advantage menu, every Medigap carrier in Indiana and the full Part D lineup, and its lineups change every October as carriers chase one of the fastest-growing retirement markets in the Midwest. IU Health North, Ascension St. Vincent Carmel and Franciscan Health Carmel each sign their own Advantage contracts, and the downtown Indianapolis flagships are twenty minutes down Meridian Street.",
          "Carmel also sends more retirees to Florida and Arizona each winter than almost anywhere in Indiana; our snowbirds guide covers which plans travel. We compare what is sold at your ZIP code with your doctors and calendar in hand."],
         ["IU Health North Hospital", "Ascension St. Vincent Carmel", "Franciscan Health Carmel", "IU Health Methodist and Ascension St. Vincent Indianapolis (downtown flagships)"],
         "Carmel, Zionsville, Westfield, West Clay, Home Place, Meridian Hills, Nora, Traders Point",
         [("Which Medicare plans are available in Carmel?", "Hamilton County typically offers dozens of Medicare Advantage plans, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is IU Health North in my plan&rsquo;s network?", "It depends on the plan and the year, and IU Health Plans&rsquo; own Advantage members were moved under Anthem for 2026. We confirm your hospital and doctors are in-network before you enroll, or steer you to a Medigap policy if you want no network at all."),
          ("How much does your help cost?", COST)],
         ["fishers", "noblesville", "indianapolis"]),
    city("fishers", "Fishers", "Hamilton County", "central-indiana", "farm",
         "Fishers and Geist sit between IU Health Saxony, Community Hospital North and the Hamilton County hospitals to the west &mdash; a deep menu, and a network map that needs reading.",
         ["Hamilton County offers dozens of Advantage plans, every Medigap carrier in Indiana and the full Part D lineup. IU Health Saxony Hospital in Fishers, Community Hospital North just across the county line, and the Carmel and Noblesville hospitals a few miles west each contract with different carriers, so which system your doctors belong to shapes the shortlist.",
          "Fishers is young for a Medicare market, which means many residents are turning 65 for the first time with employer coverage from Lilly, Roche, the state or a school corporation still in hand; when to take Part B is often the first question. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["IU Health Saxony Hospital (Fishers)", "Community Hospital North", "IU Health North and Ascension St. Vincent Carmel", "Riverview Health (Noblesville)"],
         "Fishers, Geist, Fall Creek Township, Delaware Township, McCordsville, Fortville, Lawrence-area families",
         [("Which Medicare plans are available in Fishers?", "Hamilton County typically offers dozens of Medicare Advantage plans, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I&rsquo;m still working at 65. Do I need Part B now?", "Not always. With qualifying coverage from an employer of 20 or more people you can usually delay Part B without penalty and get a Special Enrollment Period later. The rules depend on the employer&rsquo;s size and whether the drug coverage is creditable, so confirm before you decide."),
          ("How much does your help cost?", COST)],
         ["carmel", "noblesville", "indianapolis"]),
    city("noblesville", "Noblesville", "Hamilton County", "central-indiana", "courthouse",
         "The county seat has its own independent hospital, Riverview Health, plus the Carmel and Fishers hospitals a short drive south &mdash; and the deep Hamilton County plan menu to go with them.",
         ["Hamilton County offers dozens of Advantage plans, every Medigap carrier in Indiana and the full Part D lineup. Riverview Health in Noblesville is independent and contracts on its own terms; IU Health North, Ascension St. Vincent Carmel and IU Health Saxony are each a few miles away and contract differently again. Which of them your doctors belong to is the first thing we check.",
          "Noblesville, Cicero and the Morse Reservoir towns are also lake-and-winter-away country; our snowbirds guide covers which plans travel. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Riverview Health Noblesville Hospital", "IU Health North Hospital (Carmel)", "Ascension St. Vincent Carmel", "IU Health Saxony Hospital (Fishers)"],
         "Noblesville, Cicero, Arcadia, Atlanta, Sheridan, Westfield, Morse Reservoir, Lapel-area families",
         [("Which Medicare plans are available in Noblesville?", "Hamilton County typically offers dozens of Medicare Advantage plans, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Riverview Health in my plan&rsquo;s network?", "Riverview is independent and contracts with some Advantage plans and not others, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["fishers", "carmel", "anderson"]),
    city("greenwood", "Greenwood", "Johnson County", "central-indiana", "farm",
         "Greenwood and the south side have Community Hospital South and Franciscan Health Indianapolis at their door and Johnson Memorial in Franklin down the road, each contracting on its own terms.",
         ["Johnson County offers a deep Advantage menu, every Medigap carrier in Indiana and the full Part D lineup, with the downtown Indianapolis flagships twenty minutes up U.S. 31. Community Hospital South, Franciscan Health Indianapolis &mdash; the south side&rsquo;s full-service heart and vascular program &mdash; and Johnson Memorial Health in Franklin each sign their own Advantage contracts, so which of them your doctors belong to shapes the shortlist.",
          "Camp Atterbury sits at the county&rsquo;s southern edge, and a lot of Johnson County retirees are veterans who use the Roudebush VA; the Part B timing question for VA users is on our Veterans page. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Community Hospital South", "Franciscan Health Indianapolis", "Johnson Memorial Health (Franklin)", "Richard L. Roudebush VA Medical Center and Camp Atterbury clinic"],
         "Greenwood, Southport, Franklin, Whiteland, New Whiteland, Bargersville, Center Grove, Edinburgh-area families",
         [("Which Medicare plans are available in Greenwood?", "Johnson County typically offers a deep Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Franciscan Health Indianapolis in my plan&rsquo;s network?", "It depends on the plan and the year. Franciscan, Community South and Johnson Memorial contract with different Advantage carriers; with Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["indianapolis", "columbus", "bloomington"]),
    city("kokomo", "Kokomo", "Howard County", "central-indiana", "courthouse",
         "The City of Firsts is an auto-plant town with two hospitals, Ascension St. Vincent Kokomo and Community Howard, and a retiree population that mostly reaches 65 with a union plan in hand.",
         ["Howard County offers a moderate Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Ascension St. Vincent Kokomo and Community Howard Regional Health contract with different carriers, and because patients drive in from Peru, Tipton, Logansport and Greentown, a plan&rsquo;s network has to reach the whole north-central corridor; Indianapolis specialists are an hour south on U.S. 31.",
          "Kokomo&rsquo;s retirees are heavily industrial, and a union retiree plan is often the best coverage available and often a one-way door if you leave it. We set it beside the individual options honestly before anyone cancels anything. Grissom Air Reserve Base, a few miles north, adds a small military-retiree layer with TRICARE For Life."],
         ["Ascension St. Vincent Kokomo", "Community Howard Regional Health", "IU Health and Ascension St. Vincent specialists in Indianapolis"],
         "Kokomo, Greentown, Russiaville, Peru, Tipton, Logansport, Galveston, Sharpsville",
         [("Which Medicare plans are available in Kokomo?", "Howard County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I have a union retiree plan. Should I keep it?", "Compare before you cancel anything. Retiree plans usually become a group Advantage plan or a group supplement at 65, the drug coverage is normally creditable, and leaving is often permanent. We set it beside the individual options with the numbers."),
          ("How much does your help cost?", COST)],
         ["anderson", "lafayette", "fort-wayne"]),
    city("anderson", "Anderson", "Madison County", "central-indiana", "farm",
         "Anderson is a former auto town between Indianapolis and Muncie, with Ascension St. Vincent Anderson at its center and a lot of retirees whose first Medicare question is what to do with a retiree plan.",
         ["Madison County offers a moderate Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Ascension St. Vincent Anderson is the city&rsquo;s anchor hospital, and Indianapolis&rsquo;s flagships are forty minutes down I-69, which an Advantage network may or may not include; IU Health Ball Memorial in Muncie is the other direction.",
          "A large share of Anderson&rsquo;s retirees carry a union retiree plan from the auto years, and whether to keep it &mdash; and what it becomes at 65 &mdash; is usually the first thing we look at. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Ascension St. Vincent Anderson", "IU Health and Ascension St. Vincent specialists in Indianapolis", "IU Health Ball Memorial Hospital (Muncie)"],
         "Anderson, Pendleton, Chesterfield, Alexandria, Elwood, Lapel, Ingalls, Frankton",
         [("Which Medicare plans are available in Anderson?", "Madison County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I use Indianapolis specialists with an Anderson Advantage plan?", "Only if they are in that plan&rsquo;s network, which varies. With Original Medicare and a Medigap policy, any Indianapolis provider that accepts Medicare is covered. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["muncie", "noblesville", "indianapolis"]),
    city("bloomington", "Bloomington", "Monroe County", "south-central-indiana", "quarry",
         "Bloomington has IU Health&rsquo;s new Regional Academic Health Center, Monroe Hospital, a university retiree population, and a plan that changed hands for 2026.",
         ["Monroe County offers a moderate Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. IU Health Bloomington, the 2021 hospital at the Regional Academic Health Center beside the IU campus, and Monroe Hospital contract with different carriers, and Indianapolis is an hour up State Road 37 for anything the county does not do.",
          "Monroe County was IU Health Plans territory, and its Advantage members were moved under Anthem for 2026 after Elevance Health bought the plan; if that was you, confirm your doctors are in the new plan this fall. Indiana University retirees usually arrive at 65 with a retiree plan that needs its own look first."],
         ["IU Health Bloomington Hospital (Regional Academic Health Center)", "Monroe Hospital", "Bloomington VA clinic (Roudebush VA)", "IU Health specialists in Indianapolis"],
         "Bloomington, Ellettsville, Nashville, Bedford, Spencer, Bloomfield, Lake Monroe, Brown County families",
         [("Which Medicare plans are available in Bloomington?", "Monroe County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I was on IU Health Plans in Bloomington. What happened?", MOVED),
          ("How much does your help cost?", COST)],
         ["columbus", "greenwood", "evansville"]),
    city("hammond", "Hammond", "Lake County", "northwest-indiana", "mill",
         "Hammond, Munster and Highland sit on the Illinois line with Community Hospital in Munster and Franciscan Health Munster at their door, and half their specialists in Chicago.",
         ["Lake County offers a wide Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Community Healthcare System&rsquo;s flagship, Community Hospital in Munster, and Franciscan Health Munster contract with different carriers, Methodist Hospitals&rsquo; Northlake campus in Gary is minutes east, and a great many north-Lake County residents see doctors in Chicago &mdash; which an Indiana Advantage network may or may not include.",
          "Hammond&rsquo;s retirees are steel, rail and refinery families, and a union or company retiree plan is often the starting point. We set it beside the individual options, confirm your doctors on both sides of the state line, and lay Advantage beside a Medigap policy."],
         ["Community Hospital (Munster)", "Franciscan Health Munster", "Methodist Hospitals Northlake (Gary)", "Chicago-area hospitals (network-dependent)"],
         "Hammond, Munster, Highland, Whiting, Griffith, Dyer, Schererville, St. John, East Chicago, Calumet City-area families",
         [("Which Medicare plans are available in Hammond?", "Lake County typically offers a wide Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I keep my Chicago specialist with an Indiana plan?", "With Original Medicare and a Medigap policy, yes. With a Medicare Advantage plan, only if that Illinois provider is in the plan&rsquo;s network, which we confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["gary", "south-bend"]),
    city("gary", "Gary", "Lake County", "northwest-indiana", "dunes",
         "Gary and Merrillville are Methodist Hospitals country &mdash; Northlake and Southlake &mdash; with Franciscan Health Crown Point to the south, the Dunes to the east, and a steel-retiree population with union plans to sort out.",
         ["Lake County offers a wide Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Methodist Hospitals&rsquo; two campuses, Northlake in Gary and Southlake in Merrillville, and Franciscan Health&rsquo;s new Crown Point hospital contract with different carriers, and Chicago is forty minutes west for anything the Region does not do.",
          "Gary&rsquo;s retirees are largely steelworkers and their families, and a union retiree plan is frequently the best coverage on the table and a one-way door if you leave it; we compare before anyone cancels anything. Porter County&rsquo;s dune towns just east add a snowbird population whose plans need to travel."],
         ["Methodist Hospitals Northlake (Gary)", "Methodist Hospitals Southlake (Merrillville)", "Franciscan Health Crown Point", "Northwest Health Porter (Valparaiso)"],
         "Gary, Merrillville, Hobart, Crown Point, Portage, Lake Station, Chesterton, Valparaiso, Miller Beach",
         [("Which Medicare plans are available in Gary and Merrillville?", "Lake County typically offers a wide Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Methodist Hospitals in my plan&rsquo;s network?", "Methodist, Franciscan and Community Healthcare System contract with different Advantage plans, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["hammond", "south-bend"]),
    city("lafayette", "Lafayette", "Tippecanoe County", "west-central-indiana", "farm",
         "Lafayette and West Lafayette are a two-system town &mdash; IU Health Arnett and Franciscan Health &mdash; with Purdue&rsquo;s retirees and a plan menu that serves the whole upper Wabash Valley.",
         ["Tippecanoe County offers a solid Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. IU Health Arnett Hospital and Franciscan Health Lafayette East contract with different carriers, and because patients drive in from Frankfort, Monticello, Crawfordsville and Fowler, a plan&rsquo;s network has to reach the whole region; Indianapolis is an hour down I-65.",
          "Purdue and Subaru retirees usually reach 65 with employer or retiree coverage that needs a decision first, and veterans use the Roudebush VA&rsquo;s Lafayette clinic. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["IU Health Arnett Hospital", "Franciscan Health Lafayette East", "Lafayette VA clinic (Roudebush VA)"],
         "Lafayette, West Lafayette, Dayton, Battle Ground, Frankfort, Monticello, Delphi, Crawfordsville, Fowler",
         [("Which Medicare plans are available in Lafayette?", "Tippecanoe County typically offers a solid Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is IU Health Arnett in my plan&rsquo;s network?", "IU Health Arnett and Franciscan Health Lafayette contract with different Advantage plans, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["kokomo", "terre-haute", "indianapolis"]),
    city("muncie", "Muncie", "Delaware County", "east-central-indiana", "farm",
         "Muncie is a one-hospital town &mdash; IU Health Ball Memorial &mdash; that serves a dozen counties, with Ball State retirees, glass-and-auto retirees, and an Advantage plan that moved under Anthem for 2026.",
         ["Delaware County offers a moderate Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. IU Health Ball Memorial Hospital, Muncie&rsquo;s only hospital and an academic teaching hospital, draws patients from Hartford City, Portland, Winchester and New Castle, so a plan&rsquo;s network needs to include it and reach the counties around it; Indianapolis is an hour down I-69.",
          "Muncie was IU Health Plans country, and those Advantage members received Anthem plans for 2026 after Elevance Health bought the plan; if that was you, confirm your Ball Memorial doctors are in the new plan this fall. Many Muncie retirees also carry a union retiree plan that needs its own look."],
         ["IU Health Ball Memorial Hospital", "IU Health specialists in Indianapolis", "Reid Health (Richmond)"],
         "Muncie, Yorktown, Daleville, Albany, Selma, Hartford City, Winchester, Portland, New Castle-area families",
         [("Which Medicare plans are available in Muncie?", "Delaware County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I was on IU Health Plans in Muncie. What happened?", MOVED),
          ("How much does your help cost?", COST)],
         ["anderson", "fort-wayne", "indianapolis"]),
    city("terre-haute", "Terre Haute", "Vigo County", "west-central-indiana", "coveredbridge",
         "Terre Haute serves the whole lower Wabash Valley and the Illinois counties across the river, with a moderate plan menu and a 2025 plan closure that many residents still need to re-check.",
         ["Vigo County offers a moderate Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Terre Haute Regional Hospital and the city&rsquo;s other hospital system contract with different carriers, patients drive in from Brazil, Sullivan, Clinton and Rockville, and some residents use Illinois providers, which an Indiana Advantage network may or may not include.",
          "Health Alliance, the Carle-owned Advantage plan sold in parts of the Wabash Valley, closed at the end of 2025; if you were on it, the Annual Election Period is when to confirm the plan you landed in actually fits. Veterans use the Roudebush VA&rsquo;s Terre Haute clinic; how that coordinates with Medicare is on our Veterans page."],
         ["Terre Haute Regional Hospital", "Terre Haute VA clinic (Roudebush VA)", "IU Health and Ascension St. Vincent specialists in Indianapolis"],
         "Terre Haute, West Terre Haute, Brazil, Sullivan, Clinton, Rockville, Marshall-area and Paris, Illinois-area families",
         [("Which Medicare plans are available in Terre Haute?", "Vigo County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("My Advantage plan closed at the end of 2025. What now?", MOVED),
          ("How much does your help cost?", COST)],
         ["lafayette", "bloomington", "indianapolis"]),
    city("elkhart", "Elkhart", "Elkhart County", "north-central-indiana", "lakes",
         "The RV capital has Elkhart General (Beacon) and Goshen Health, a retiree population that often reaches 65 straight off a factory floor with employer coverage, and Michigan a few miles north.",
         ["Elkhart County offers a solid Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Elkhart General Hospital, part of Beacon Health System, and Goshen Health contract with different carriers, and South Bend&rsquo;s systems are twenty minutes west, so which one your doctors belong to shapes the shortlist.",
          "Elkhart&rsquo;s RV and manufacturing workers frequently work past 65 with employer coverage in hand; when to take Part B, and what happens to the drug coverage, is usually the first question. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Elkhart General Hospital (Beacon)", "Goshen Health", "Memorial Hospital of South Bend (Beacon)", "Saint Joseph Health System Mishawaka Medical Center"],
         "Elkhart, Goshen, Bristol, Middlebury, Nappanee, Wakarusa, Dunlap, Simonton Lake, Michigan-line families",
         [("Which Medicare plans are available in Elkhart?", "Elkhart County typically offers a solid Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I&rsquo;m still working at 65 with employer coverage. Do I need Part B now?", "Not always. With qualifying coverage from an employer of 20 or more people you can usually delay Part B without penalty and get a Special Enrollment Period later. Confirm the employer&rsquo;s size and whether the drug coverage is creditable before you decide."),
          ("How much does your help cost?", COST)],
         ["mishawaka", "south-bend", "fort-wayne"]),
    city("mishawaka", "Mishawaka", "St. Joseph County", "north-central-indiana", "lakes",
         "Mishawaka is home to Saint Joseph Health System&rsquo;s main campus, with Beacon&rsquo;s hospitals a few miles either side &mdash; the two-system question in its purest form.",
         ["St. Joseph County offers a solid Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Saint Joseph Health System&rsquo;s Mishawaka Medical Center and Beacon&rsquo;s Memorial Hospital of South Bend and Beacon Granger contract with different carriers, so a plan that includes one may exclude the other, and the lists change every October.",
          "Mishawaka and Granger also have a sizeable snowbird population; our snowbirds guide covers which plans travel. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Saint Joseph Health System Mishawaka Medical Center", "Memorial Hospital of South Bend (Beacon)", "Beacon Granger Hospital", "Elkhart General Hospital (Beacon)"],
         "Mishawaka, Granger, Osceola, Penn Township, Harris Township, Wakarusa-area families",
         [("Which Medicare plans are available in Mishawaka?", "St. Joseph County typically offers a solid Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Saint Joseph Health System in my plan&rsquo;s network?", "It depends on the plan and the year. Saint Joseph and Beacon contract with different Advantage carriers; with Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["south-bend", "elkhart"]),
    city("columbus", "Columbus", "Bartholomew County", "south-central-indiana", "coveredbridge",
         "Columbus has an independent hospital, Columbus Regional Health, a large Cummins retiree population with a retiree plan to think about, and Indianapolis forty-five minutes up I-65.",
         ["Bartholomew County offers a moderate Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Columbus Regional Health is independent and contracts on its own terms; Schneck Medical Center in Seymour serves the south end of the county; and Indianapolis&rsquo;s systems are up the interstate for anything beyond that, which an Advantage network may or may not include.",
          "Cummins retirees usually arrive at 65 with a retiree plan, and whether to keep it is the first question we answer; the second is whether the plan you are considering includes Columbus Regional. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Columbus Regional Health", "Schneck Medical Center (Seymour)", "IU Health and Franciscan specialists in Indianapolis"],
         "Columbus, Hope, Edinburgh, Taylorsville, Seymour, North Vernon, Nashville-area families",
         [("Which Medicare plans are available in Columbus?", "Bartholomew County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Columbus Regional Health in my plan&rsquo;s network?", "Columbus Regional is independent and contracts with some Advantage plans and not others, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["bloomington", "greenwood", "jeffersonville-new-albany"]),
    city("jeffersonville-new-albany", "Jeffersonville &amp; New Albany", "Clark and Floyd counties", "southeast-indiana", "river",
         "Southern Indiana&rsquo;s river cities are part of metro Louisville: their hospitals are run by Louisville systems, their specialists are across the bridge, and whether a plan reaches Kentucky is the whole question.",
         ["Clark and Floyd counties offer a moderate Advantage menu, every Medigap carrier in Indiana and the full Part D lineup. Clark Memorial Health in Jeffersonville is run by Norton Healthcare and LifePoint Health; Baptist Health Floyd in New Albany belongs to Kentucky&rsquo;s Baptist Health; and most specialty referrals go to Norton, Baptist or UofL Health in Louisville. Some Indiana Advantage plans include those Louisville providers; most do not, and the list changes every October.",
          "That is why so many families here keep Original Medicare with a Medigap policy: it covers both sides of the river with no network to check, and with Indiana&rsquo;s birthday rule the premium can be shopped every year. Fort Knox retirees who settled on the Indiana side carry TRICARE For Life, which changes the calculation; see our Veterans page."],
         ["Clark Memorial Health (Jeffersonville)", "Baptist Health Floyd (New Albany)", "Louisville hospitals across the river (network-dependent)"],
         "Jeffersonville, New Albany, Clarksville, Sellersburg, Charlestown, Floyds Knobs, Georgetown, Corydon, Scottsburg-area families",
         [("Which Medicare plans are available in Jeffersonville and New Albany?", "Clark and Floyd counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Indiana, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("My doctors are in Louisville. Which plan works?", "With Original Medicare and a Medigap policy, any Louisville provider that accepts Medicare is covered. With a Medicare Advantage plan, only if that provider is in the plan&rsquo;s network, which we confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["columbus", "evansville", "bloomington"]),
]

# Indiana has no large active-duty installation with a Medicare-age retiree community of its own; Naval Support Activity
# Crane and Grissom Air Reserve Base are covered on the Veterans page and the nearby city pages instead.
BASES = []
