"""Ohio regions, cities and military communities."""
COST = "Nothing. Independent agents are paid by the carriers when you enroll, so comparing plans and reviewing your coverage each year is free to you."
EXIT = ("For the 2026 plan year Medical Mutual of Ohio did not renew some of its plans in 44 counties, Aetna ended its Smart Fit plan, and the national carriers trimmed county footprints across Ohio; Humana has announced further reductions for 2027. "
        "A plan leaving your county gives you a Special Enrollment Period and, in most cases, a guaranteed-issue right to a Medigap policy without health questions. Ohio has no birthday rule to fall back on later, so use the window.")
SYSTEMS = "Each system contracts with some Advantage plans and not others, and the contracts change every year. With Original Medicare and a Medigap policy there is no network to check. We confirm your doctors&rsquo; status for the specific plan before you enroll."

REGIONS = [
    dict(slug="northeast-ohio", name="Northeast Ohio", short="Northeast Ohio", scene="erie",
         eyebrow="Medicare by region · Cleveland, Akron, Canton, Youngstown &amp; the lake counties",
         h1="Medicare help across Northeast Ohio",
         sub="Cuyahoga, Summit, Stark, Mahoning, Lorain, Lake and the counties around them &mdash; the deepest Medicare Advantage menus in Ohio, three big Cleveland systems that contract separately, and the home turf of Medical Mutual and SummaCare.",
         counties="Cuyahoga, Lake, Geauga, Ashtabula, Lorain, Medina, Summit, Portage, Stark, Wayne, Holmes, Mahoning, Trumbull, Columbiana, Ashland, Richland, Crawford",
         cities=["cleveland", "parma", "lakewood", "lorain", "elyria", "akron", "canton", "youngstown", "mansfield"],
         systems=["Cleveland Clinic", "University Hospitals", "MetroHealth", "Summa Health", "Cleveland Clinic Akron General", "Aultman Health", "Cleveland Clinic Mercy Hospital (Canton)", "Mercy Health Youngstown", "Louis Stokes Cleveland VA Medical Center"],
         note="<p><strong>Local plans to know:</strong> Cuyahoga and Summit are among the four Ohio counties where KFF counted 80 or more Advantage plans for 2025. Medical Mutual of Ohio is headquartered in Cleveland and SummaCare, owned by Summa Health, sells across 25 northern Ohio counties. Cleveland Clinic, University Hospitals and MetroHealth each contract on their own terms, so a $0-premium plan that includes one may exclude another.</p>",
         intro=["More people on Medicare live in Northeast Ohio than in any other part of the state, and the plan menu shows it: dozens of Medicare Advantage plans in Cuyahoga, Summit, Lorain and Stark, every Medigap carrier licensed in Ohio, and the full Part D lineup. The trade-off is that the region&rsquo;s care is organized into large systems that contract separately &mdash; Cleveland Clinic, University Hospitals and MetroHealth in Greater Cleveland, Summa and Cleveland Clinic Akron General in Akron, Aultman and Cleveland Clinic Mercy in Canton, Mercy Health in the Mahoning Valley &mdash; so the first question is which system your doctors belong to.",
                "Toward Ashtabula, the Amish counties and the Mahoning Valley the menu thins, and 2026 brought Medical Mutual non-renewals in a number of counties. The region is also union country: the UAW trust, the steelworker plans and the city and county retiree plans each set their own Medicare rules. We compare what is sold at your ZIP code with your doctors, your pharmacy and your retiree coverage in front of us."],
         faqs=[("Which Medicare plans are available in Cleveland and Akron?", "Cuyahoga and Summit counties typically have the widest choice in Ohio: dozens of Medicare Advantage plans from Medical Mutual, SummaCare, Humana, UnitedHealthcare, Aetna, Anthem and others, every Medigap carrier in the state, and all standalone Part D plans. Availability is set by county and ZIP code and changes each plan year."),
               ("Are Cleveland Clinic and University Hospitals in the same plans?", "Rarely both in every plan. Each contracts with some Advantage carriers and not others, and the lists change yearly; with Original Medicare and a Medigap policy there is no network to check. If you use both systems, or expect a referral to either, we confirm the plan&rsquo;s status in writing before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="central-ohio", name="Central Ohio", short="Central Ohio", scene="scioto",
         eyebrow="Medicare by region · Columbus, Delaware, Newark, Lancaster &amp; Marion",
         h1="Medicare help across Central Ohio",
         sub="Franklin, Delaware, Licking, Fairfield and the counties around Columbus &mdash; the fastest-growing Medicare market in Ohio, three systems that contract separately, a hospital-owned plan in MediGold, and more OPERS and STRS retirees than anywhere else in the state.",
         counties="Franklin, Delaware, Licking, Fairfield, Pickaway, Madison, Union, Morrow, Knox, Marion, Fayette",
         cities=["columbus", "newark", "lancaster", "defense-supply-center-columbus"],
         systems=["The Ohio State University Wexner Medical Center", "OhioHealth", "Mount Carmel Health System", "Licking Memorial Health Systems", "Fairfield Medical Center", "Chalmers P. Wylie VA Ambulatory Care Center"],
         note="<p><strong>Local plans to know:</strong> MediGold is owned by Mount Carmel and Trinity Health and sells Advantage plans built on that system. OSU Wexner and OhioHealth contract with different carriers, and the James, Ohio State&rsquo;s cancer hospital, is the referral that decides a lot of central Ohio plan choices. Columbus is also the seat of OPERS and STRS, whose retiree rules shape more Medicare decisions here than any brochure.</p>",
         intro=["Central Ohio has one of the deepest Medicare menus in the state and a care map split three ways: Ohio State&rsquo;s Wexner Medical Center and the James, OhioHealth&rsquo;s Riverside, Grant and Dublin hospitals, and Mount Carmel&rsquo;s East and Grove City campuses. Each signs its own Advantage contracts, and MediGold sells plans built on Mount Carmel, so the first question is never the premium; it is which system your doctors belong to.",
                "Outside the I-270 ring the menu thins quickly. Newark leans on Licking Memorial, Lancaster on Fairfield Medical Center, Marion on OhioHealth Marion General, and the Advantage lineups in those counties are shorter and shifted for 2026. Central Ohio also holds the largest concentration of state, university and school-district retirees in Ohio, whose OPERS, STRS and SERS coverage decides the shape of their Medicare before anything else does."],
         faqs=[("Which Medicare plans are available in Columbus?", "Franklin and Delaware counties typically offer a wide Medicare Advantage menu, including MediGold, Medical Mutual and the national carriers, every Medigap carrier in Ohio, and the full Part D lineup. Availability is set by county and ZIP code and changes each plan year."),
               ("Is OSU Wexner or the James in my plan&rsquo;s network?", "OSU Wexner accepts Original Medicare and therefore any Medigap policy. It contracts with some Advantage plans and not others, and the list changes yearly. If the James or another OSU program is your care, we confirm the plan&rsquo;s status in writing before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="southwest-ohio", name="Southwest Ohio", short="Southwest Ohio", scene="roebling",
         eyebrow="Medicare by region · Cincinnati, Dayton, Hamilton, Middletown &amp; Wright-Patterson",
         h1="Medicare help across Southwest Ohio",
         sub="Hamilton, Butler, Warren, Clermont, Montgomery and Greene counties &mdash; Cincinnati&rsquo;s four systems, Dayton&rsquo;s two, a tri-state care map that crosses into Kentucky, and the Air Force retiree community around Wright-Patterson.",
         counties="Hamilton, Butler, Warren, Clermont, Clinton, Brown, Montgomery, Greene",
         cities=["cincinnati", "hamilton", "dayton", "kettering", "wright-patterson-afb"],
         systems=["UC Health", "TriHealth", "The Christ Hospital Health Network", "Mercy Health Cincinnati", "Premier Health", "Kettering Health", "Cincinnati VA Medical Center", "Dayton VA Medical Center"],
         note="<p><strong>What to watch:</strong> Cincinnati&rsquo;s care is split among UC Health, TriHealth, The Christ Hospital and Mercy Health, and many residents also use St. Elizabeth across the river in Kentucky, which an Ohio Advantage network may or may not include. Dayton is Premier Health and Kettering Health country, and Wright-Patterson&rsquo;s retirees carry TRICARE For Life on top of Medicare, which changes what &ldquo;best plan&rdquo; means.</p>",
         intro=["Southwest Ohio has two big Medicare markets a short drive apart. Cincinnati and its suburbs have a deep Advantage menu and a four-system care map, with the extra wrinkle that a lot of care happens in Northern Kentucky. Dayton&rsquo;s menu is nearly as deep, split between Premier Health&rsquo;s Miami Valley hospitals and Kettering Health&rsquo;s campuses across the Miami Valley, and both systems contract plan by plan.",
                "The region also holds one of the Air Force&rsquo;s largest retiree communities around Wright-Patterson, where TRICARE For Life makes a Medigap policy and a Part D plan usually unnecessary, and a large GM, Honda-supplier and steel retiree population in Dayton, Hamilton and Middletown whose union plans set their own rules. For 2026 Medical Mutual and Aetna both trimmed plans in parts of the region; a non-renewal notice opens a time-limited guaranteed-issue window for Medigap."],
         faqs=[("Which Medicare plans are available in Cincinnati and Dayton?", "Hamilton and Montgomery counties typically offer a wide Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup. Clinton and Brown counties have fewer Advantage plans. We compare what is sold at your address."),
               ("I have TRICARE For Life from Wright-Patterson. Which plan should I look at?", "With TFL you already have a supplement-like layer and creditable drug coverage, so a Medigap policy and a Part D plan are usually unnecessary. An MA-only Advantage plan can add dental or vision without duplicating drug coverage. See our Wright-Patterson and Veterans pages."),
               ("How much does your help cost?", COST)]),
    dict(slug="northwest-ohio", name="Northwest Ohio", short="Northwest Ohio", scene="maumee",
         eyebrow="Medicare by region · Toledo, Findlay, Lima, Sandusky &amp; the lake shore",
         h1="Medicare help across Northwest Ohio",
         sub="Lucas, Wood, Hancock, Allen, Erie, Sandusky and the flat farm counties between &mdash; ProMedica and Mercy Health in Toledo, strong regional hospitals in Findlay and Lima, and a Paramount plan that now belongs to Medical Mutual.",
         counties="Lucas, Wood, Fulton, Williams, Defiance, Henry, Paulding, Putnam, Van Wert, Allen, Hancock, Hardin, Wyandot, Seneca, Sandusky, Ottawa, Erie, Huron",
         cities=["toledo", "findlay"],
         systems=["ProMedica", "Mercy Health Toledo", "University of Toledo Medical Center", "Blanchard Valley Health System (Findlay)", "Mercy Health &ndash; St. Rita&rsquo;s (Lima)"],
         note="<p><strong>Local plans to know:</strong> Paramount, long ProMedica&rsquo;s insurance arm, became part of Medical Mutual in 2024, and Medical Mutual and ProMedica only settled their 2026 network contract in November 2025 &mdash; a reminder that a system can be in a plan one year and out the next. UAW retirees from the Toledo Jeep and transmission plants carry Trust coverage with its own Part B rules.</p>",
         intro=["Toledo has a moderate Advantage menu split between ProMedica and Mercy Health, with the University of Toledo Medical Center as the region&rsquo;s academic hospital. Because patients drive in from Bowling Green, Fremont, Defiance and Bryan, a plan&rsquo;s network has to reach the whole corner of the state, and the ProMedica&ndash;Medical Mutual dispute that ran into late 2025 showed how much that matters.",
                "South and west of Toledo the counties are flat, farmed and thinly served: Findlay leans on Blanchard Valley, Lima on Mercy Health St. Rita&rsquo;s, and the counties between on one hospital apiece. Advantage menus are shorter here and shifted for 2026, which is where Original Medicare with a Medigap policy earns its keep."],
         faqs=[("Which Medicare plans are available in Toledo?", "Lucas and Wood counties typically offer a moderate Medicare Advantage menu, including Medical Mutual&rsquo;s Paramount Elite plans, every Medigap carrier in Ohio, and the full Part D lineup. The rural counties to the south and west have fewer Advantage plans."),
               ("Is ProMedica in my plan&rsquo;s network?", "ProMedica and Mercy Health contract with different Advantage plans, and ProMedica&rsquo;s contract with Medical Mutual was only renewed in November 2025 after a public dispute. With Original Medicare and a Medigap policy there is no network to check. We confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="west-central-ohio", name="West Central Ohio", short="West Central Ohio", scene="amish",
         eyebrow="Medicare by region · Springfield, Troy, Sidney, Bellefontaine &amp; the Miami Valley farm counties",
         h1="Medicare help across West Central Ohio",
         sub="Clark, Miami, Shelby, Logan, Champaign, Darke, Mercer, Auglaize and Preble counties &mdash; Springfield&rsquo;s regional hospital, a ring of county hospitals, and Dayton&rsquo;s specialists a short drive away.",
         counties="Clark, Champaign, Logan, Miami, Shelby, Darke, Mercer, Auglaize, Preble",
         cities=["springfield"],
         systems=["Mercy Health &ndash; Springfield Regional Medical Center", "Premier Health &ndash; Upper Valley Medical Center (Troy)", "Wilson Health (Sidney)", "Mary Rutan Hospital (Bellefontaine)", "Kettering Health and Premier Health (Dayton referrals)"],
         note="<p><strong>What to watch:</strong> Most of the region&rsquo;s specialty care happens in Dayton, so an Advantage plan sold in Shelby or Darke County has to include the Dayton system your doctors refer to. Honda&rsquo;s Marysville and Anna plants and the Springfield and Piqua manufacturing base mean a lot of retirees here carry employer or union coverage with its own Medicare rules.</p>",
         intro=["West Central Ohio is county-hospital country: Springfield Regional in Clark County, Upper Valley in Troy, Wilson in Sidney, Mary Rutan in Bellefontaine, and Mercer Health and Joint Township in the far west, with Dayton&rsquo;s Premier Health and Kettering Health handling the referrals. Advantage menus are moderate in Clark and Miami counties and shorter farther out, and several counties saw plans withdrawn for 2026.",
                "For a lot of families here the practical answer is Original Medicare with a Medigap policy, which works at the county hospital and in Dayton alike without a network question. We compare that against the Advantage plans actually sold at your ZIP code, with your doctors and your retiree coverage in hand."],
         faqs=[("Which Medicare plans are available in Springfield and Troy?", "Clark and Miami counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup. The farm counties to the west have fewer Advantage plans and some lost plans for 2026."),
               ("My Advantage plan is leaving my county. What now?", EXIT),
               ("How much does your help cost?", COST)]),
    dict(slug="east-ohio-appalachian", name="East Ohio &amp; the Appalachian counties", short="East Ohio", scene="ohioriver",
         eyebrow="Medicare by region · Zanesville, Cambridge, Steubenville, New Philadelphia &amp; the river counties",
         h1="Medicare help across East Ohio and the Appalachian counties",
         sub="Muskingum, Tuscarawas, Jefferson, Belmont, Guernsey and the hill counties between &mdash; Genesis in Zanesville, Trinity in Steubenville, Cleveland Clinic Union in Dover, long drives, and some of the thinnest Advantage menus in Ohio.",
         counties="Muskingum, Coshocton, Tuscarawas, Carroll, Harrison, Jefferson, Belmont, Guernsey, Noble, Monroe, Perry",
         cities=["zanesville"],
         systems=["Genesis HealthCare System (Zanesville)", "Trinity Health System (Steubenville)", "Cleveland Clinic Union Hospital (Dover)", "OhioHealth Southeastern Medical Center (Cambridge)", "Wheeling Hospital (WVU Medicine, across the river)"],
         note="<p><strong>What to watch:</strong> East Ohio&rsquo;s counties have fewer carriers than the metros and several saw Medical Mutual non-renewals for 2026. A lot of care crosses the river into Wheeling and Pittsburgh, which an Ohio Advantage network may not include; Original Medicare with a Medigap policy covers all of it without a network.</p>",
         intro=["East Ohio Medicare is a distance problem. Zanesville, Cambridge, Dover&ndash;New Philadelphia and Steubenville each have a solid regional hospital, but the hill counties between may be an hour from any of them, and referrals run to Columbus, Cleveland, Wheeling and Pittsburgh. Advantage networks that look fine on paper can be a long drive in practice, and for 2026 several counties out here lost plans.",
                "That is why so many East Ohioans keep Original Medicare with a Medigap policy: it works at Genesis, Trinity and Union alike, across the river, and at the Columbus or Cleveland systems a referral points to. Coal, steel and utility retirees add union plans with their own Medicare rules; the retiree coverage page covers them."],
         faqs=[("Which Medicare plans are available in Zanesville or Steubenville?", "Muskingum and Jefferson counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup. The rural counties around them have fewer Advantage plans and some lost plans for 2026."),
               ("Can I use a Wheeling or Pittsburgh hospital with an Ohio plan?", "With Original Medicare and a Medigap policy, yes &mdash; any provider that accepts Medicare. With a Medicare Advantage plan, only if the out-of-state hospital is in that plan&rsquo;s network, which we confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="southeast-ohio-river", name="Southeast Ohio &amp; the Ohio River", short="Southeast Ohio", scene="ohioriver",
         eyebrow="Medicare by region · Marietta, Athens, Gallipolis, Ironton &amp; the river towns",
         h1="Medicare help across Southeast Ohio and the Ohio River valley",
         sub="Washington, Athens, Meigs, Gallia, Lawrence and Morgan counties &mdash; Marietta Memorial, OhioHealth O&rsquo;Bleness, Holzer, and a care map that crosses into West Virginia and Kentucky.",
         counties="Washington, Athens, Meigs, Gallia, Lawrence, Morgan",
         cities=[],
         systems=["Memorial Health System (Marietta)", "OhioHealth O&rsquo;Bleness Hospital (Athens)", "Holzer Health System (Gallipolis, Jackson)", "Camden Clark Medical Center (WVU Medicine, Parkersburg)", "Huntington, WV and Ashland, KY systems (across the river)"],
         note="<p><strong>What to watch:</strong> The river counties have some of the shortest Advantage menus in Ohio, and a large share of care happens in Parkersburg, Huntington and Ashland across the river. Ask specifically whether an Ohio plan&rsquo;s network reaches those hospitals; a Medigap policy does without asking.</p>",
         intro=["Southeast Ohio runs along the river from Marietta to Ironton, and its health care does too: Marietta Memorial, O&rsquo;Bleness in Athens and Holzer in Gallipolis on the Ohio side, Camden Clark, Cabell Huntington and King&rsquo;s Daughters on the other. Advantage plans are sold by Ohio county and draw their networks around Ohio systems, so the first question we ask is where your doctors actually are.",
                "Advantage menus here are short and got shorter for 2026. For most families along the river the practical answer is Original Medicare with a Medigap policy, which pays on both banks, plus a Part D plan chosen around the pharmacy you use. We serve every town in the region by phone and video."],
         faqs=[("Which Medicare plans are available in Marietta and Athens?", "Washington and Athens counties typically offer a shorter Medicare Advantage menu than the metros, every Medigap carrier in Ohio, and the full Part D lineup. Availability is set by county and changes each plan year."),
               ("Can I use a hospital in Parkersburg or Huntington with an Ohio plan?", "With Original Medicare and a Medigap policy, yes &mdash; any provider that accepts Medicare, in any state. With a Medicare Advantage plan, only if that hospital is in the plan&rsquo;s network, which we confirm in writing before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="south-central-ohio", name="South Central Ohio", short="South Central Ohio", scene="hocking",
         eyebrow="Medicare by region · Chillicothe, Portsmouth, Logan, Jackson, Hillsboro &amp; the Hocking Hills",
         h1="Medicare help across South Central Ohio",
         sub="Ross, Scioto, Pike, Jackson, Adams, Highland, Vinton and Hocking counties &mdash; Adena in Chillicothe, Southern Ohio Medical Center in Portsmouth, the Chillicothe VA, and Columbus specialists an hour up Route 23.",
         counties="Ross, Pike, Scioto, Adams, Highland, Jackson, Vinton, Hocking",
         cities=[],
         systems=["Adena Health (Chillicothe)", "Southern Ohio Medical Center (Portsmouth)", "Chillicothe VA Medical Center", "Adena Pike Medical Center (Waverly)", "Hocking Valley Community Hospital (Logan)"],
         note="<p><strong>What to watch:</strong> Adena serves most of the region and refers to Columbus; SOMC anchors the Portsmouth end. The Chillicothe VA is a full medical center and the mental-health referral center for southern Ohio, so a lot of veterans here carry VA care and Medicare together, and the Part B timing rule matters.</p>",
         intro=["South Central Ohio has two regional systems, Adena in Chillicothe and Southern Ohio Medical Center in Portsmouth, a ring of small county hospitals, and Columbus an hour north for anything they refer out. Advantage menus are moderate in Ross and Scioto counties and short in Vinton, Pike and Adams, and several counties saw plans withdrawn for 2026.",
                "The region also has one of Ohio&rsquo;s larger veteran populations relative to its size, served by the Chillicothe VA Medical Center; how VA care coordinates with Medicare is on our Veterans page. We compare what is sold at your ZIP code with your doctors, the pharmacy you actually use, and any retiree or VA coverage in hand, and serve every town in the region by phone and video."],
         faqs=[("Which Medicare plans are available in Chillicothe and Portsmouth?", "Ross and Scioto counties typically offer a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup. The smaller counties around them have fewer Advantage plans and some lost plans for 2026."),
               ("I use the Chillicothe VA. Do I still need Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying it can trigger a permanent penalty and leaves you without coverage at Adena, SOMC or a Columbus hospital. VA pharmacy is creditable for Part D."),
               ("How much does your help cost?", COST)]),
]

def city(slug, name, county, region, scene, sub, intro, systems, communities, faqs, nearby):
    return dict(slug=slug, name=name, county=county, region=region, scene=scene, sub=sub, intro=intro, systems=systems, communities=communities, faqs=faqs, nearby=nearby)

CITIES = [
    city("columbus", "Columbus", "Franklin County", "central-ohio", "scioto",
         "From Clintonville to Grove City, Columbus has one of the deepest Medicare menus in Ohio &mdash; and three hospital systems that each contract on their own terms. The comparison here starts with which of them your doctors belong to.",
         ["Franklin County offers dozens of Medicare Advantage plans, every Medigap carrier licensed in Ohio and the full Part D lineup. The catch is that Columbus care is organized into three systems that sign their own contracts: Ohio State&rsquo;s Wexner Medical Center and the James, OhioHealth&rsquo;s Riverside, Grant and Doctors hospitals, and Mount Carmel, whose parent also owns MediGold, an Advantage plan built on that system. A plan that includes OhioHealth may exclude OSU, or the reverse.",
          "Columbus is also the seat of OPERS and STRS, and a large share of the city&rsquo;s retirees reach Medicare with a pension plan that decides the next step: an HRA through Via Benefits for OPERS, the Aetna Medicare plan for STRS and SERS. We compare what is actually offered at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a supplement so you can see the trade-off plainly."],
         ["The Ohio State University Wexner Medical Center &amp; the James", "OhioHealth (Riverside Methodist, Grant, Doctors, Dublin Methodist)", "Mount Carmel Health System", "Chalmers P. Wylie VA Ambulatory Care Center"],
         "Clintonville, Upper Arlington, Bexley, Worthington, Westerville, Dublin, Hilliard, Grove City, Gahanna, Reynoldsburg, Whitehall, Delaware, Pickerington, Canal Winchester",
         [("Which Medicare plans are available in Columbus?", "Franklin County typically has one of the widest choices in Ohio: dozens of Medicare Advantage plans including MediGold and Medical Mutual, every Medigap carrier in the state, and all standalone Part D plans. Availability is set by ZIP code and changes each plan year; we compare what is offered at your address."),
          ("Will my OSU or OhioHealth doctors take a Medicare Advantage plan?", "It depends on the specific plan&rsquo;s network, and the contracts change every year. Before you enroll we confirm your providers at OSU Wexner, OhioHealth or Mount Carmel are in-network and your prescriptions are on the formulary, so there are no surprises in January."),
          ("How much does your help cost?", COST)],
         ["defense-supply-center-columbus", "newark", "lancaster"]),
    city("cleveland", "Cleveland", "Cuyahoga County", "northeast-ohio", "erie",
         "Cuyahoga County has one of the deepest Medicare Advantage menus in the country and a care map split three ways: Cleveland Clinic, University Hospitals and MetroHealth each contract with different plans.",
         ["Cleveland offers dozens of Medicare Advantage plans &mdash; KFF counted 80 or more in Cuyahoga County for 2025 &mdash; plus every Medigap carrier in Ohio and the full Part D lineup. The network question is the whole question: Cleveland Clinic&rsquo;s main campus and community hospitals, University Hospitals&rsquo; Cleveland Medical Center and its suburban hospitals, and MetroHealth each sign their own Advantage contracts, and Medical Mutual, headquartered downtown, sells plans against the national carriers.",
          "Cleveland is also home to the Louis Stokes VA Medical Center, which serves 24 northeast Ohio counties, and to a large union-retiree population whose UAW, steelworker and city plans set their own Medicare rules. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy so the trade-off is plain."],
         ["Cleveland Clinic (main campus and community hospitals)", "University Hospitals Cleveland Medical Center", "MetroHealth", "Louis Stokes Cleveland VA Medical Center"],
         "Downtown, Ohio City, Tremont, University Circle, Shaker Heights, Cleveland Heights, Euclid, Garfield Heights, Maple Heights, Brook Park, Strongsville, Westlake, Rocky River, Beachwood, Mayfield",
         [("Which Medicare plans are available in Cleveland?", "Cuyahoga County typically offers one of the widest Medicare Advantage menus in the country, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Cleveland Clinic in my Advantage plan&rsquo;s network?", "Cleveland Clinic accepts Original Medicare and therefore any Medigap policy, and contracts with some Advantage plans and not others; so do University Hospitals and MetroHealth. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["parma", "lakewood", "lorain", "akron"]),
    city("cincinnati", "Cincinnati", "Hamilton County", "southwest-ohio", "roebling",
         "Cincinnati&rsquo;s Medicare menu is broad and its care map is split four ways &mdash; UC Health, TriHealth, The Christ Hospital and Mercy Health &mdash; with a fifth system, St. Elizabeth, across the river in Kentucky.",
         ["Hamilton County offers a wide Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. UC Health&rsquo;s University of Cincinnati Medical Center, TriHealth&rsquo;s Good Samaritan and Bethesda North, The Christ Hospital and Mercy Health&rsquo;s Cincinnati hospitals each contract with different carriers, so which system your doctors belong to shapes the shortlist; many Cincinnatians also use St. Elizabeth in Northern Kentucky, which an Ohio plan&rsquo;s network may or may not include.",
          "The Cincinnati VA Medical Center, with divisions in Cincinnati and Fort Thomas, Kentucky, serves 17 counties in three states. Cincinnati retirees travel more than most, and a lot of them winter in Florida, which is where a Medigap policy&rsquo;s any-provider access matters. We compare both paths with your doctors and your calendar in front of us."],
         ["UC Health &ndash; University of Cincinnati Medical Center", "TriHealth (Good Samaritan, Bethesda North)", "The Christ Hospital Health Network", "Mercy Health Cincinnati", "Cincinnati VA Medical Center"],
         "Hyde Park, Oakley, Mt. Lookout, Westwood, Price Hill, Clifton, Anderson Township, Blue Ash, Montgomery, Sharonville, Norwood, Colerain Township, Green Township, Delhi, Mason, Loveland, Milford",
         [("Which Medicare plans are available in Cincinnati?", "Hamilton County typically offers a wide Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I use St. Elizabeth in Kentucky with an Ohio plan?", "With Original Medicare and a Medigap policy, yes. With a Medicare Advantage plan, only if St. Elizabeth is in that plan&rsquo;s network, which we confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["hamilton", "dayton", "kettering"]),
    city("toledo", "Toledo", "Lucas County", "northwest-ohio", "maumee",
         "The Glass City has two hospital systems, an academic medical center, a Paramount plan that now belongs to Medical Mutual, and a large UAW retiree population from the Jeep and transmission plants.",
         ["Lucas County offers a moderate Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. ProMedica Toledo Hospital, Mercy Health St. Vincent Medical Center and the University of Toledo Medical Center contract with different carriers, and the public dispute between ProMedica and Medical Mutual that ran until November 2025 showed how a system can drop out of a plan&rsquo;s network for a year.",
          "Toledo&rsquo;s auto retirees carry UAW Retiree Medical Benefits Trust coverage, which pays as if they have Parts A and B whether or not they enrolled &mdash; a rule that costs people who skip Part B. We compare what is sold at your ZIP code with your doctors, your pharmacy and your retiree coverage in hand."],
         ["ProMedica Toledo Hospital", "Mercy Health &ndash; St. Vincent Medical Center", "University of Toledo Medical Center", "ProMedica Flower Hospital (Sylvania)"],
         "Old West End, Ottawa Hills, Sylvania, Maumee, Perrysburg, Oregon, Rossford, Holland, Waterville, Bowling Green, Northwood, Point Place",
         [("Which Medicare plans are available in Toledo?", "Lucas County typically offers a moderate Medicare Advantage menu, including Medical Mutual&rsquo;s Paramount Elite plans and the national carriers, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is ProMedica in my plan&rsquo;s network?", "ProMedica and Mercy Health contract with different Advantage plans, and ProMedica&rsquo;s contract with Medical Mutual was only renewed in November 2025. With Original Medicare and a Medigap policy there is no network to check. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["findlay", "lorain", "elyria"]),
    city("akron", "Akron", "Summit County", "northeast-ohio", "millvalley",
         "The Rubber City has one of the four deepest Advantage menus in Ohio, two systems that contract separately, and a hospital-owned plan of its own in SummaCare.",
         ["Summit County is one of the four Ohio counties where KFF counted 80 or more Medicare Advantage plans for 2025, and it has every Medigap carrier in Ohio and the full Part D lineup. Summa Health, now part of HATCo, and Cleveland Clinic Akron General contract with different carriers, and SummaCare, owned by Summa, sells plans built on that system across 25 northern Ohio counties.",
          "Akron&rsquo;s Goodyear, Bridgestone and steel retirees carry union and employer plans with their own Medicare rules, and Summit County residents often use Cleveland specialists too. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Summa Health (Akron Campus)", "Cleveland Clinic Akron General", "Akron VA community clinic (VA Northeast Ohio)"],
         "Highland Square, Ellet, Firestone Park, Fairlawn, Cuyahoga Falls, Stow, Hudson, Tallmadge, Barberton, Norton, Green, Copley, Bath",
         [("Which Medicare plans are available in Akron?", "Summit County typically offers one of the deepest Medicare Advantage menus in Ohio, including SummaCare and Medical Mutual, every Medigap carrier in the state, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Are Summa and Akron General in the same plans?", "Not always. Each contracts with some Advantage carriers and not others, and SummaCare is built on Summa. With Original Medicare and a Medigap policy there is no network to check. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["canton", "cleveland", "parma"]),
    city("dayton", "Dayton", "Montgomery County", "southwest-ohio", "flightline",
         "Dayton&rsquo;s Medicare menu is deep and split between Premier Health and Kettering Health, with Wright-Patterson&rsquo;s Air Force retirees and the Dayton VA adding two more layers to the question.",
         ["Montgomery County offers a wide Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Premier Health&rsquo;s Miami Valley Hospital and Kettering Health&rsquo;s campuses across the Miami Valley contract with different carriers, so which system your doctors belong to shapes the shortlist before price does.",
          "Dayton is also an Air Force town. Wright-Patterson&rsquo;s retirees reach 65 with TRICARE For Life, which makes a Medigap policy and a Part D plan usually unnecessary; veterans without TFL use the Dayton VA Medical Center and need Part B on time. GM and Delphi retirees carry UAW trust coverage with its own rules. We sort out which layers you have and compare from there."],
         ["Premier Health &ndash; Miami Valley Hospital", "Kettering Health (Dayton, Main Campus)", "Dayton VA Medical Center", "Wright-Patterson Medical Center (TRICARE)"],
         "Oakwood, Huber Heights, Trotwood, Riverside, Vandalia, Englewood, Centerville, Miamisburg, West Carrollton, Beavercreek, Fairborn, Xenia",
         [("Which Medicare plans are available in Dayton?", "Montgomery County typically offers a wide Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("I have TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit. See our Wright-Patterson page."),
          ("How much does your help cost?", COST)],
         ["wright-patterson-afb", "kettering", "springfield", "cincinnati"]),
    city("parma", "Parma", "Cuyahoga County", "northeast-ohio", "erie",
         "Parma, Parma Heights and the southwest suburbs have Cuyahoga County&rsquo;s deep menu, University Hospitals Parma on their doorstep, and Cleveland Clinic and MetroHealth minutes away.",
         ["Cuyahoga County&rsquo;s Advantage menu is one of the deepest in the country, and Parma residents can reach all three Cleveland systems. University Hospitals Parma Medical Center is the neighborhood hospital; Cleveland Clinic and MetroHealth are the referrals; and which of the three a plan includes is the first thing we check.",
          "Parma is also one of the most union-retiree-heavy suburbs in Ohio, with GM, steel and city retirees whose plans set their own Medicare rules. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["University Hospitals Parma Medical Center", "Cleveland Clinic", "MetroHealth", "Parma VA community clinic (VA Northeast Ohio)"],
         "Parma, Parma Heights, Seven Hills, Brooklyn, Brook Park, Middleburg Heights, Broadview Heights, North Royalton, Independence",
         [("Which Medicare plans are available in Parma?", "Cuyahoga County typically offers one of the widest Medicare Advantage menus in the country, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is UH Parma in my plan&rsquo;s network?", "University Hospitals contracts with some Advantage plans and not others, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["cleveland", "lakewood", "akron"]),
    city("canton", "Canton", "Stark County", "northeast-ohio", "millvalley",
         "Canton and Stark County have two hospitals that contract separately &mdash; Aultman and Cleveland Clinic Mercy &mdash; and serve a five-county region that reaches into Amish country.",
         ["Stark County offers a deep Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Aultman Hospital, the county&rsquo;s largest hospital and employer, and Cleveland Clinic Mercy Hospital serve Stark, Carroll, Wayne, Holmes and Tuscarawas counties and contract with different carriers, so which one your doctors use shapes the shortlist.",
          "Because patients drive in from Massillon, Alliance, Carrollton and Millersburg, a plan&rsquo;s network has to reach the whole region, and the Amish and rural counties to the south have shorter menus that shifted for 2026. Timken and steel retirees add union plans with their own Medicare rules."],
         ["Aultman Hospital", "Cleveland Clinic Mercy Hospital", "Canton VA community clinic (VA Northeast Ohio)"],
         "Canton, North Canton, Massillon, Alliance, Louisville, Jackson Township, Plain Township, Perry Township, Minerva, Carrollton",
         [("Which Medicare plans are available in Canton?", "Stark County typically offers a deep Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Aultman in my plan&rsquo;s network?", "Aultman and Cleveland Clinic Mercy contract with different Advantage plans, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["akron", "youngstown", "mansfield"]),
    city("youngstown", "Youngstown", "Mahoning County", "northeast-ohio", "millvalley",
         "The Mahoning Valley has Mercy Health at its center, a Warren hospital that closed and reopened under new ownership in 2025, and one of the largest steel and auto retiree populations in Ohio.",
         ["Mahoning and Trumbull counties offer a moderate Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Mercy Health&rsquo;s St. Elizabeth Youngstown and St. Elizabeth Boardman hospitals anchor the Valley; in Warren, Trumbull Regional Medical Center closed in March 2025 after the Steward bankruptcy and reopened as Insight Hospital &amp; Medical Center Trumbull in October 2025, while the Hillside rehabilitation hospital stayed closed. That is exactly the kind of change that can leave a plan&rsquo;s network thinner than its brochure.",
          "The Valley&rsquo;s steelworker, GM Lordstown and utility retirees carry union and trust coverage with their own Part B rules, and a lot of specialty care runs to Cleveland or Pittsburgh. We compare what is sold at your ZIP code with your doctors, your pharmacy and your retiree coverage in hand."],
         ["Mercy Health &ndash; St. Elizabeth Youngstown Hospital", "Mercy Health &ndash; St. Elizabeth Boardman Hospital", "Insight Hospital &amp; Medical Center Trumbull (Warren)", "Youngstown VA community clinic (VA Northeast Ohio)"],
         "Youngstown, Boardman, Austintown, Canfield, Poland, Struthers, Campbell, Warren, Niles, Girard, Hubbard, Cortland, Columbiana",
         [("Which Medicare plans are available in Youngstown?", "Mahoning County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Insight Trumbull in Warren back in the plan networks?", "Insight Hospital &amp; Medical Center Trumbull reopened in October 2025 after a six-month closure. Whether a given Advantage plan lists it in-network for 2026 is plan-specific, and we confirm it in writing before you enroll; a Medigap policy covers any hospital that accepts Medicare."),
          ("How much does your help cost?", COST)],
         ["canton", "akron", "cleveland"]),
    city("lorain", "Lorain", "Lorain County", "northeast-ohio", "erie",
         "Lorain and the lake shore have Mercy Health Lorain Hospital, University Hospitals in Elyria, Cleveland&rsquo;s systems half an hour east, and a large steel and auto retiree population from the mill and the Ford plant.",
         ["Lorain County offers a deep Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Mercy Health Lorain Hospital and University Hospitals Elyria Medical Center contract with different carriers, and Cleveland Clinic and UH each have suburban hospitals within a short drive, so which system your doctors belong to shapes the shortlist.",
          "Lorain&rsquo;s U.S. Steel and Ford Avon Lake retirees carry union and UAW trust coverage with its own Medicare rules. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Mercy Health &ndash; Lorain Hospital", "University Hospitals Elyria Medical Center", "Cleveland Clinic Avon Hospital", "Lorain County VA community clinic (VA Northeast Ohio)"],
         "Lorain, Sheffield Lake, Sheffield, Avon, Avon Lake, Amherst, Vermilion, South Amherst",
         [("Which Medicare plans are available in Lorain?", "Lorain County typically offers a deep Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Mercy Health Lorain in my plan&rsquo;s network?", "Mercy Health and University Hospitals contract with different Advantage plans, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["elyria", "lakewood", "cleveland"]),
    city("hamilton", "Hamilton", "Butler County", "southwest-ohio", "roebling",
         "Hamilton, Fairfield and Middletown sit between Cincinnati and Dayton with Butler County&rsquo;s wide menu and hospitals from three different systems &mdash; Kettering Health, Mercy Health and TriHealth.",
         ["Butler County offers a wide Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Kettering Health Hamilton (the former Fort Hamilton Hospital), Mercy Health Fairfield Hospital and TriHealth&rsquo;s Bethesda Butler and McCullough-Hyde hospitals each contract separately, and because the county sits between two metros, plans built on Cincinnati systems and plans built on Dayton systems both sell here.",
          "Hamilton and Middletown are also steel towns, with AK Steel and other union retirees whose plans set their own Medicare rules. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Kettering Health Hamilton", "Mercy Health &ndash; Fairfield Hospital", "TriHealth Bethesda Butler Hospital", "TriHealth McCullough-Hyde Memorial Hospital (Oxford)"],
         "Hamilton, Fairfield, Fairfield Township, Middletown, Trenton, Oxford, West Chester Township, Liberty Township, Monroe, Ross Township",
         [("Which Medicare plans are available in Hamilton?", "Butler County typically offers a wide Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Kettering Health Hamilton in my plan&rsquo;s network?", "It depends on the plan and the year; Kettering Health, Mercy Health and TriHealth each contract separately. We confirm your hospital and doctors are in-network before you enroll."),
          ("How much does your help cost?", COST)],
         ["cincinnati", "dayton", "kettering"]),
    city("springfield", "Springfield", "Clark County", "west-central-ohio", "amish",
         "Springfield and Clark County have one regional hospital, Mercy Health Springfield Regional, Dayton&rsquo;s two systems half an hour west, and a plan menu that is moderate in the city and short in the farm counties around it.",
         ["Clark County offers a moderate Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Mercy Health&rsquo;s Springfield Regional Medical Center is the county&rsquo;s hospital, and referrals run to Kettering Health and Premier Health in Dayton or to OSU in Columbus, which an Advantage network may or may not include.",
          "Springfield&rsquo;s manufacturing retirees carry union and employer plans with their own Medicare rules, and Wright-Patterson&rsquo;s retirees spill into the county with TRICARE For Life. We compare what is sold at your ZIP code with your doctors, your pharmacy and your retiree coverage in hand."],
         ["Mercy Health &ndash; Springfield Regional Medical Center", "Kettering Health and Premier Health (Dayton referrals)", "Wright-Patterson Medical Center (TRICARE)"],
         "Springfield, Enon, New Carlisle, Northridge, South Vienna, Urbana, Yellow Springs, Fairborn-area families",
         [("Which Medicare plans are available in Springfield?", "Clark County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Can I use Dayton specialists with a Springfield Advantage plan?", "Only if they are in that plan&rsquo;s network, which varies. With Original Medicare and a Medigap policy, any Dayton or Columbus provider that accepts Medicare is covered. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["dayton", "wright-patterson-afb", "kettering"]),
    city("kettering", "Kettering", "Montgomery County", "southwest-ohio", "flightline",
         "Kettering, Centerville and Oakwood are Kettering Health&rsquo;s home ground, with Premier Health across town, Wright-Patterson&rsquo;s retirees next door, and Montgomery County&rsquo;s wide plan menu.",
         ["Montgomery County offers a wide Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Kettering Health&rsquo;s Main Campus is the neighborhood hospital, Premier Health&rsquo;s Miami Valley South is minutes away, and the two systems contract with different carriers, so which one your doctors belong to shapes the shortlist.",
          "Kettering&rsquo;s south-suburban retirees include a large share of Wright-Patterson and NCR retirees; TRICARE For Life and employer retiree plans each change the calculation. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Kettering Health Main Campus", "Premier Health &ndash; Miami Valley Hospital South", "Dayton VA Medical Center", "Wright-Patterson Medical Center (TRICARE)"],
         "Kettering, Oakwood, Centerville, Washington Township, Moraine, West Carrollton, Miamisburg, Springboro, Bellbrook, Sugarcreek Township",
         [("Which Medicare plans are available in Kettering?", "Montgomery County typically offers a wide Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Kettering Health Main Campus in my plan&rsquo;s network?", "Kettering Health and Premier Health contract with different Advantage plans, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["dayton", "wright-patterson-afb", "hamilton"]),
    city("elyria", "Elyria", "Lorain County", "northeast-ohio", "erie",
         "Elyria is University Hospitals&rsquo; base in Lorain County, with Mercy Health in Lorain, Cleveland Clinic in Avon, and the county&rsquo;s deep plan menu.",
         ["Lorain County offers a deep Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. University Hospitals Elyria Medical Center, Mercy Health Lorain Hospital and Cleveland Clinic Avon Hospital each belong to a different system that contracts separately, and Cleveland&rsquo;s main campuses are half an hour east.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy &mdash; with any union or employer retiree coverage in hand."],
         ["University Hospitals Elyria Medical Center", "Mercy Health &ndash; Lorain Hospital", "Cleveland Clinic Avon Hospital"],
         "Elyria, North Ridgeville, Grafton, Oberlin, Wellington, LaGrange, Carlisle Township, Eaton Township",
         [("Which Medicare plans are available in Elyria?", "Lorain County typically offers a deep Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is UH Elyria in my plan&rsquo;s network?", "University Hospitals, Mercy Health and Cleveland Clinic contract with different Advantage plans. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["lorain", "cleveland", "lakewood"]),
    city("lakewood", "Lakewood", "Cuyahoga County", "northeast-ohio", "erie",
         "Lakewood and the west-shore suburbs have Cuyahoga County&rsquo;s deep menu, Cleveland Clinic&rsquo;s Lakewood Family Health Center and Fairview Hospital, and MetroHealth and UH close by.",
         ["Cuyahoga County&rsquo;s Advantage menu is one of the deepest in the country. Since Lakewood Hospital closed, Cleveland Clinic&rsquo;s Lakewood Family Health Center on Detroit Avenue has been the neighborhood&rsquo;s front door, with its physicians admitting to Fairview Hospital; University Hospitals St. John in Westlake and MetroHealth are the alternatives, and each system contracts with different plans.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Cleveland Clinic Lakewood Family Health Center", "Cleveland Clinic Fairview Hospital", "University Hospitals St. John Medical Center (Westlake)", "MetroHealth"],
         "Lakewood, Rocky River, Bay Village, Westlake, Fairview Park, North Olmsted, Detroit-Shoreway, Cudell",
         [("Which Medicare plans are available in Lakewood?", "Cuyahoga County typically offers one of the widest Medicare Advantage menus in the country, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Fairview Hospital in my plan&rsquo;s network?", "Cleveland Clinic contracts with some Advantage plans and not others, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["cleveland", "parma", "lorain"]),
    city("newark", "Newark", "Licking County", "central-ohio", "scioto",
         "Newark, Heath and Granville have Licking Memorial as their hospital, Columbus&rsquo;s three systems forty minutes west, and one of the fastest-growing Medicare markets in central Ohio.",
         ["Licking County offers a moderate Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Licking Memorial Hospital is the county&rsquo;s independent hospital, and referrals run to OSU, OhioHealth and Mount Carmel in Columbus, which an Advantage network may or may not include.",
          "Licking County is growing fast and its plan lineup changes every October as carriers follow it. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Licking Memorial Hospital", "OSU Wexner, OhioHealth and Mount Carmel (Columbus referrals)", "Newark VA community clinic (VA Central Ohio)"],
         "Newark, Heath, Granville, Hebron, Pataskala, Johnstown, Utica, Buckeye Lake, Etna Township",
         [("Which Medicare plans are available in Newark?", "Licking County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Licking Memorial in my plan&rsquo;s network?", "It depends on the plan and the year. We confirm your hospital and doctors are in-network before you enroll, or steer you to a Medigap policy if you want no network at all."),
          ("How much does your help cost?", COST)],
         ["columbus", "lancaster", "zanesville"]),
    city("mansfield", "Mansfield", "Richland County", "northeast-ohio", "buckeye",
         "Mansfield and Ontario have two hospital systems that contract separately, OhioHealth Mansfield and Avita, and sit halfway between Columbus and Cleveland for anything they refer out.",
         ["Richland County offers a moderate Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. OhioHealth Mansfield Hospital and Avita Health System&rsquo;s Ontario Hospital contract with different carriers, and because patients drive in from Ashland, Bucyrus, Galion and Shelby, a plan&rsquo;s network has to reach the whole north-central region.",
          "Mansfield&rsquo;s steel and manufacturing retirees carry union plans with their own Medicare rules. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["OhioHealth Mansfield Hospital", "Avita Health System (Ontario, Galion, Bucyrus)", "Mansfield VA community clinic (VA Northeast Ohio)"],
         "Mansfield, Ontario, Lexington, Shelby, Bellville, Ashland, Galion, Bucyrus, Crestline",
         [("Which Medicare plans are available in Mansfield?", "Richland County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is OhioHealth Mansfield in my plan&rsquo;s network?", "OhioHealth and Avita contract with different Advantage plans, changing year to year. With Original Medicare and a Medigap policy there is no network. We confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["canton", "columbus", "akron"]),
    city("findlay", "Findlay", "Hancock County", "northwest-ohio", "maumee",
         "Findlay serves the flat farm counties of northwest Ohio with Blanchard Valley Hospital, Toledo and Columbus specialists an hour away, and a plan menu that is shorter than the metros.",
         ["Hancock County offers a moderate Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Blanchard Valley Health System&rsquo;s Findlay hospital is the region&rsquo;s anchor, and referrals run to ProMedica or Mercy in Toledo or to OSU in Columbus, which an Advantage network may or may not include.",
          "The counties around Findlay &mdash; Putnam, Wyandot, Hardin, Seneca &mdash; have shorter menus that shifted for 2026. Original Medicare with a Medigap policy works at Blanchard Valley and in Toledo alike, which is why it is the practical answer for many families out here; Marathon and Whirlpool retirees add employer plans with their own rules."],
         ["Blanchard Valley Hospital (Findlay)", "ProMedica and Mercy Health (Toledo referrals)", "Mercy Health &ndash; St. Rita&rsquo;s (Lima)"],
         "Findlay, Fostoria, Tiffin, Bluffton, Ottawa, Upper Sandusky, Carey, North Baltimore, Arlington, Van Buren",
         [("Which Medicare plans are available in Findlay?", "Hancock County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup. Surrounding counties have fewer Advantage plans and some lost plans for 2026."),
          ("My plan pulled out of my county near Findlay. What now?", EXIT),
          ("How much does your help cost?", COST)],
         ["toledo", "mansfield"]),
    city("zanesville", "Zanesville", "Muskingum County", "east-ohio-appalachian", "ohioriver",
         "Zanesville is East Ohio&rsquo;s medical hub, with Genesis Hospital serving a six-county region where the Advantage menu is short and got shorter for 2026.",
         ["Muskingum County offers a moderate Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Genesis HealthCare System&rsquo;s Zanesville hospital is the region&rsquo;s anchor, and because patients drive in from Coshocton, Cambridge, New Lexington and McConnelsville, a plan&rsquo;s network has to reach the whole hill country; referrals run to Columbus, which an Advantage network may or may not include.",
          "Several East Ohio counties lost Advantage plans for 2026; a non-renewal notice opens a time-limited guaranteed-issue window for a Medigap policy, which works at Genesis and at OSU or OhioHealth alike."],
         ["Genesis Hospital (Zanesville)", "OSU Wexner, OhioHealth and Mount Carmel (Columbus referrals)", "Zanesville VA community clinic (VA Central Ohio)"],
         "Zanesville, South Zanesville, Dresden, New Concord, Coshocton, Cambridge, New Lexington, McConnelsville, Crooksville",
         [("Which Medicare plans are available in Zanesville?", "Muskingum County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup. Surrounding counties have fewer Advantage plans and some lost plans for 2026."),
          ("My plan is leaving my East Ohio county. What now?", EXIT),
          ("How much does your help cost?", COST)],
         ["newark", "lancaster", "columbus"]),
    city("lancaster", "Lancaster", "Fairfield County", "central-ohio", "hocking",
         "Lancaster sits at the edge of the Hocking Hills with an independent hospital, Fairfield Medical Center, and Columbus&rsquo;s three systems half an hour north.",
         ["Fairfield County offers a moderate Advantage menu, every Medigap carrier in Ohio and the full Part D lineup. Fairfield Medical Center remains independent &mdash; a planned affiliation with OhioHealth fell through in 2025 and it has since explored a partnership with Adena &mdash; and referrals run to OSU, OhioHealth and Mount Carmel in Columbus, which an Advantage network may or may not include.",
          "Pickerington and Canal Winchester at the county&rsquo;s north end are effectively Columbus suburbs with Columbus lineups; Lancaster and the Hocking Hills end are thinner. We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Fairfield Medical Center", "OSU Wexner, OhioHealth and Mount Carmel (Columbus referrals)", "Hocking Valley Community Hospital (Logan)"],
         "Lancaster, Pickerington, Canal Winchester, Carroll, Baltimore, Bremen, Amanda, Logan, Sugar Grove",
         [("Which Medicare plans are available in Lancaster?", "Fairfield County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Ohio, and the full Part D lineup, set by ZIP code and changing each plan year."),
          ("Is Fairfield Medical Center in my plan&rsquo;s network?", "It depends on the plan and the year. We confirm your hospital and doctors are in-network before you enroll, or steer you to a Medigap policy if you want no network at all."),
          ("How much does your help cost?", COST)],
         ["columbus", "newark", "zanesville"]),
]

BASES = [
    dict(slug="wright-patterson-afb", name="Wright-Patterson AFB (Dayton)", region="southwest-ohio", scene="flightline",
         title="Medicare Near Wright-Patterson AFB &amp; Dayton, OH | ECOS Medicare Solutions",
         desc="Medicare for military retirees and veterans around Wright-Patterson Air Force Base, Fairborn, Beavercreek and Dayton: TRICARE For Life, Wright-Patterson Medical Center, the Dayton VA, and which plans fit. From a retired Air Force officer.",
         h1="Medicare near Wright-Patterson Air Force Base, Fairborn and Beavercreek",
         sub="One of the Air Force&rsquo;s largest retiree communities lives around Wright-Patt. TRICARE For Life, Wright-Patterson Medical Center, the Dayton VA &mdash; and a Medicare decision that looks different from a civilian one.",
         h2="Why the Medicare choice is different for a Wright-Patterson family",
         intro=["Greene and Montgomery counties hold a large community of Air Force retirees and their spouses, and most of them reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left to decide is whether an MA-only Advantage plan adds dental, vision or hearing worth having &mdash; without duplicating the drug coverage you already have.",
                "Veterans without TRICARE use the Dayton VA Medical Center, and here the Part B timing question is the one that matters: VA care is not creditable for Part B, so delaying Part B because you have the VA triggers a lifelong penalty. Wright-Patterson Medical Center, run by the 88th Medical Group, continues to see retirees under TRICARE rules, and the base&rsquo;s Retiree Activities Office works with TRICARE and the Dayton VA on exactly these questions; Medicare does not pay at a military hospital."],
         systems=["Wright-Patterson Medical Center (88th Medical Group, TRICARE)", "Dayton VA Medical Center", "Kettering Health (Soin Medical Center, Beavercreek; Main Campus)", "Premier Health &ndash; Miami Valley Hospital"],
         communities="Fairborn, Beavercreek, Huber Heights, Riverside, Xenia, Bellbrook, Enon, Yellow Springs, Kettering, Springfield-area retirees",
         faqs=[("I retired from the Air Force with TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit; we check whether one is worth it for you."),
               ("I use the Dayton VA. Do I still need Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying it can trigger a permanent penalty and leaves you without coverage at a non-VA hospital. Enroll on time."),
               ("Can I keep using Wright-Patterson Medical Center after 65?", "Retirees can be seen at Wright-Patterson Medical Center under TRICARE rules; Medicare does not pay there. Most Wright-Patt retirees pair TFL with civilian care at Kettering Health or Premier Health, and the Retiree Activities Office (937-257-3221) can help with base questions.")],
         nearby=["dayton", "kettering", "springfield"], cta="Retired from Wright-Patt? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
    dict(slug="defense-supply-center-columbus", name="Defense Supply Center Columbus", region="central-ohio", scene="scioto",
         title="Medicare Near Defense Supply Center Columbus, OH | ECOS Medicare Solutions",
         desc="Medicare for military retirees and veterans in central Ohio who use the Defense Supply Center Columbus in Whitehall: TRICARE For Life, the Chalmers P. Wylie VA outpatient center, and which Columbus plans fit. From a retired Air Force officer.",
         h1="Medicare for military retirees around Defense Supply Center Columbus",
         sub="Central Ohio has no military hospital and no inpatient VA hospital, which makes the Medicare decision for a retiree here different from Dayton&rsquo;s. Here is how TRICARE For Life, the Wylie VA center and the Columbus systems fit together.",
         h2="Why the Medicare choice is different for a central Ohio military family",
         intro=["The Defense Supply Center Columbus in Whitehall, headquarters of DLA Land and Maritime, is where central Ohio&rsquo;s military retirees go for DEERS and ID cards, and thousands of Army, Air Force, Navy and Guard retirees live within a short drive of it. Most reach 65 with TRICARE For Life, which requires Medicare Parts A and B, pays secondary to Medicare and carries creditable pharmacy coverage. For a TFL family a Medigap policy and a Part D plan are usually redundant; the live question is whether an MA-only Advantage plan&rsquo;s dental, vision and hearing extras are worth having and whether its network includes the Columbus system you use.",
                "Unlike Dayton, Columbus has no military treatment facility for inpatient care and no VA hospital: the Chalmers P. Wylie VA Ambulatory Care Center is a large outpatient facility, and inpatient care is referred to OSU, OhioHealth, Mount Carmel or another VA medical center. That is why Part B matters even more here &mdash; it is what pays at the community hospital &mdash; and why we confirm which of the three Columbus systems a plan includes before anything else."],
         systems=["Chalmers P. Wylie VA Ambulatory Care Center", "The Ohio State University Wexner Medical Center", "OhioHealth", "Mount Carmel Health System", "Defense Supply Center Columbus (DEERS / ID cards; no inpatient care)"],
         communities="Whitehall, Reynoldsburg, Gahanna, Bexley, Pickerington, Canal Winchester, Groveport, Westerville, New Albany, Rickenbacker-area families",
         faqs=[("I have TRICARE For Life. Which Columbus plan should I pick?", "For most TFL families, Original Medicare Parts A and B with TFL is complete coverage. An MA-only Advantage plan can add dental, vision and hearing without duplicating your pharmacy benefit; we check whether one is worth it for you and whether its network includes your OSU, OhioHealth or Mount Carmel doctors."),
               ("Is there a VA hospital in Columbus?", "No. The Chalmers P. Wylie VA Ambulatory Care Center provides primary and specialty outpatient care; inpatient care is referred out. That makes Part B, which pays at the community hospitals, especially important for central Ohio veterans."),
               ("Does DSCC have a clinic I can use after 65?", "DSCC is a logistics installation with a DEERS and ID-card office, not a military hospital. Medicare does not pay at military facilities in any case. Most central Ohio military retirees pair TFL with civilian care at OSU, OhioHealth or Mount Carmel.")],
         nearby=["columbus", "newark", "lancaster"], cta="Retired in central Ohio? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
]
