"""Ohio FAQ page, About, Privacy, Terms."""
FAQ_PAGE = [
    ("How much does it cost to work with ECOS Medicare Solutions?", "Nothing. Independent Medicare agents are paid by the insurance carriers when you enroll, so comparing plans, answering questions and reviewing your coverage each year is free to you. Your premium is the same whether you enroll through us, another agent or the carrier directly."),
    ("My Medicare Advantage plan left my Ohio county. What now?", "You get a Special Enrollment Period to choose a new plan and, because you lost coverage through no fault of your own, generally a guaranteed-issue right to buy a Medigap policy without health questions, usually within 63 days of the coverage ending. For 2026 Medical Mutual did not renew some plans in 44 counties and Aetna ended its Smart Fit plan, so a lot of Ohioans are in this position. Ohio has no birthday rule to fall back on later, so use the window. Call before the deadline on your notice."),
    ("Does Ohio have a Medigap birthday rule or annual switching window?", "No. Your six-month Medigap open enrollment at 65 is the guaranteed window, plus guaranteed-issue events such as a plan leaving your county or, under an Ohio Department of Insurance notice, losing Ohio Medicaid. Outside those, Ohio insurers can use medical underwriting."),
    ("I am under 65 on Medicare because of a disability. Can I buy Medigap in Ohio?", "Usually not. Ohio is one of the few states that does not require insurers to sell Medigap to people under 65, so most carriers do not. Medicare Advantage plans, including Chronic and Dual Special Needs Plans and MyCare Ohio, are available under 65, and a full six-month Medigap open enrollment begins when you turn 65."),
    ("Does Cleveland Clinic, OSU Wexner or UC Health accept Medicare Advantage plans?", "Each accepts Original Medicare and therefore every Medigap policy. Each contracts with some Medicare Advantage plans and not others, and the lists change yearly; University Hospitals, MetroHealth, OhioHealth, Mount Carmel, TriHealth, Christ, Mercy Health, Premier, Kettering and ProMedica are the same. If a specific system is your care, we confirm the plan&rsquo;s status in writing before you enroll."),
    ("I am an OPERS retiree. Can you enrol me in a Medicare plan?", "Not in the plan that unlocks your HRA. OPERS deposits the allowance only when you buy a Medicare plan through Via Benefits, its connector (1-844-287-9945 for Medicare), so that enrollment has to go through Via Benefits. We help you understand the choice first &mdash; which plans include your hospital system, Medigap versus Advantage, your spouse&rsquo;s timing &mdash; so the call is short. See our retiree coverage page."),
    ("I retired from teaching or a school district. Do I need to buy a Part D plan at 65?", "Generally not. STRS Ohio and SERS Ohio enrol Medicare-eligible retirees in a group Aetna Medicare Advantage PPO that includes Part D through SilverScript, and a separate Part D plan can disrupt the group plan. Send your retirement system proof of Medicare enrollment and check with it before buying anything else."),
    ("I have TRICARE For Life from Wright-Patterson. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating the drug benefit. Our Wright-Patterson and Defense Supply Center Columbus pages walk through it."),
    ("I use the VA. Do I still need Medicare Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying it triggers a permanent penalty and leaves you without coverage at a non-VA hospital &mdash; and in Columbus, where the Wylie center is outpatient only, that is where inpatient care happens. VA pharmacy is creditable for Part D."),
    ("When can I enroll in or change my Medicare plan in Ohio?", "Your Initial Enrollment Period is the seven months around your 65th birthday. The Annual Election Period runs October 15 to December 7; Medicare Advantage Open Enrollment runs January 1 to March 31. Moving counties, losing a plan, or qualifying for Medicaid opens a Special Enrollment Period."),
    ("What are the [[YEAR]] Medicare costs?", "Part B premium $202.90 a month, Part B deductible $283, Part A hospital deductible $1,736 per benefit period, Part D out-of-pocket cap $2,100. Higher earners pay IRMAA surcharges above $109,000 (single) or $218,000 (joint) of 2024 income. Our costs page has the full chart and calculators."),
    ("Can Ohio help pay my Part B premium?", "Possibly. Ohio&rsquo;s Medicare Savings Programs (QMB, SLMB, QI), run through Ohio Medicaid, pay the Part B premium for people with limited income and resources, and QMB also covers Medicare&rsquo;s deductibles and copays. They are not subject to estate recovery and bring Part D Extra Help automatically. Apply at benefits.ohio.gov or 800-324-8680; OSHIIP (800-686-1578) helps with the form for free."),
    ("What is MyCare Ohio?", "Ohio&rsquo;s program for people with both Medicare and Medicaid. It was rebuilt on January 1, 2026 as Next Generation MyCare, a fully integrated dual-eligible special needs plan run by Anthem Blue Cross and Blue Shield, Buckeye Health Plan, CareSource or Molina Healthcare of Ohio, replacing the demonstration that ended December 31, 2025. It started in the original 29 counties and was scheduled to reach all 88 by August 1, 2026; confirm your county with the Ohio Medicaid Consumer Hotline."),
    ("Where can I get free, unbiased Medicare counseling in Ohio?", "OSHIIP, the Ohio Senior Health Insurance Information Program, is Ohio&rsquo;s State Health Insurance Assistance Program and part of the Ohio Department of Insurance since 1992: 800-686-1578, weekdays 8 to 5. You can also call 1-800-MEDICARE or use Medicare.gov. We are an independent agency, not a government program, and we say so on every page."),
    ("Do you offer every plan available in my area?", "No. We represent a number of insurance organizations and products in Ohio, not all of them, and we will always say so. For the complete list, use Medicare.gov, 1-800-MEDICARE or OSHIIP. For help choosing among the plans we do offer, call [[PHONE]]."),
    ("Where can I verify your Ohio license?", "Darin Weidauer holds Ohio insurance license #1616139 (NPN 18580338). You can verify it through the Ohio Department of Insurance Agent / Agency Locator at gateway.insurance.ohio.gov by searching the licence number or the NPN, or through the NIPR."),
    ("Do you meet in person?", "We work with Ohioans statewide by phone and video, which is how most people prefer it across 88 counties. Our sister agency has walk-in offices in Mesa and Sun City, Arizona, for Ohio snowbirds who winter there."),
]

ABOUT_BODY = """<div class="author" style="margin-bottom:2rem">
<img class="author__photo" src="/darin.jpg" width="600" height="600" alt="Darin Weidauer, independent Medicare insurance agent and credentialed gerontologist" loading="lazy" decoding="async">
<div>
<ul class="creds"><li>OH License #1616139 · NPN 18580338</li><li>Credentialed gerontologist (2014)</li><li>Registered Social Security Analyst&reg;</li><li>MBA, Pepperdine</li><li>Master&rsquo;s in Long-Term Care, USC</li><li>22-yr USAF veteran (retired officer)</li></ul>
<p>Darin Weidauer is an independent Medicare insurance agent, credentialed gerontologist, and Registered Social Security Analyst&reg; who helps Ohio retirees and people approaching 65 make sense of their Medicare options &mdash; clearly, patiently, and with no cost to them.</p>
</div></div>
<h2>Background</h2>
<p>A 22-year U.S. Air Force veteran who retired as an officer &mdash; and who knows Wright-Patterson the way every career airman does &mdash; Darin holds five master&rsquo;s degrees, including an MBA and a Master&rsquo;s in Dispute Resolution from Pepperdine University and a Master&rsquo;s in Long-Term Care from the University of Southern California&rsquo;s Leonard Davis School of Gerontology, where he became a credentialed gerontologist in 2014 &mdash; studying the human side of aging, not just the paperwork.</p>
<p>A former Professor of Aerospace Studies at Loyola Marymount University who has lectured at more than 50 colleges and universities, Darin now channels that teaching instinct into plain-English Medicare education: one-on-one reviews, no-cost community workshops, the free 295-page guide <a href="/retirement-guide"><em>Retire With Confidence</em></a>, and the pages on this site, every one of which he wrote or reviewed. He is also the founder of MyECOS360, an agency operating system for independent insurance agents, and the author of its training on <a href="https://www.myecos360.com/insurance-lead-economics">insurance lead economics</a>.</p>
<h2>How he is paid, and what that means for you</h2>
<p>ECOS Medicare Solutions is an independent agency: appointed with a number of Medicare Advantage, Medigap and Part D carriers in Ohio, employed by none of them. When you enroll in a plan through us, the carrier pays us a commission. That commission comes out of the carrier&rsquo;s filed rate &mdash; it is never added to your premium. You pay the same whether you enroll through us, through another agent, or directly with the insurer; going direct does not make a policy cheaper, and using us does not make it dearer.</p>
<p>We do not represent every plan sold in Ohio, and we say so on every page. For a complete list, use Medicare.gov, 1-800-MEDICARE, or OSHIIP (800-686-1578), the Ohio Department of Insurance&rsquo;s free and independent counseling program. And where a retirement system requires you to buy through its own connector &mdash; OPERS through Via Benefits, OP&amp;F through Alight &mdash; we tell you so and help you prepare for that call rather than compete with it.</p>
<h2>Licensing</h2>
<p>Darin Weidauer holds <strong>Ohio insurance license #1616139</strong> and is a licensed insurance agent in Ohio and fifteen other states &mdash; Arizona, California, Colorado, Georgia, Hawaii, Indiana, Minnesota, Nevada, New Mexico, North Carolina, South Carolina, Tennessee, Texas, Utah and Washington &mdash; under National Producer Number 18580338, which you can verify with the <a href="https://gateway.insurance.ohio.gov/UI/ODI.Agent.Public.UI/AgentSearch.mvc/DisplaySearch" rel="noopener">Ohio Department of Insurance Agent / Agency Locator</a> or through the NIPR. The multi-state licence is what lets us follow Ohio snowbirds to Arizona and keep their coverage straight in both directions; our Florida section has its own licensed Florida agent for the other end of I-75.</p>
<h2>Where else you will find him</h2>
<ul>
<li><a href="https://www.myecos360.com/darin-weidauer" rel="noopener">Author page at MyECOS360</a> &mdash; the canonical profile</li>
<li><a href="https://www.linkedin.com/in/darin-weidauer-3165a816b/" rel="noopener">LinkedIn</a> and <a href="https://www.youtube.com/channel/UCD1XkkknhQ3UT-8AteYD3vQ" rel="noopener">YouTube</a></li>
<li>Sister sections of this site: <a href="https://www.ecosinsurancesolutions.com/florida" rel="noopener">Florida</a> and <a href="https://www.ecosinsurancesolutions.com/arizona" rel="noopener">Arizona</a> for Ohio snowbirds, <a href="https://www.ecosinsurancesolutions.com/indiana" rel="noopener">Indiana</a> next door, and <a href="https://www.mymedigaprate.com" rel="noopener">MyMedigapRate</a>, where Medigap rate filings &mdash; Ohio&rsquo;s included &mdash; are published filing by filing.</li>
</ul>
<h2>How to reach him</h2>
<p>Call <a href="tel:[[TEL]]"><strong>[[PHONE]]</strong></a>, email <a href="mailto:[[EMAIL]]">[[EMAIL]]</a>, or use the form at the top of this page. We work with Ohioans statewide by phone and video.</p>
"""

PRIVACY_BODY = """<p style="color:var(--ink-soft)"><em>Last updated: September 13, 2026. This policy is provided as a starting template and should be reviewed by your attorney before launch.</em></p>
<p>This Privacy Policy explains how ECOS Medicare Solutions ("we," "us") handles information collected through the Ohio section of ecosinsurancesolutions.com (the "Site").</p>
<h2>Information we collect</h2>
<p>When you submit a form on the Site, we collect the information you provide: your name, phone number, email address, ZIP code or city, the topic you select, and a record of the consent you give (including the consent language shown and a date/time stamp). We do not ask for, and ask you not to send, health information through the form.</p>
<h2>How we use it</h2>
<p>We use your information to contact you about Medicare plan options and to provide the help you requested &mdash; by phone call, text message and email, consistent with the consent you provide. A licensed insurance agent may contact you. We do not sell your personal information.</p>
<h2>How your form is processed</h2>
<p>Our forms are delivered through a third-party form-processing service (Web3Forms), which transmits your submission to us. The Site loads web fonts from Google Fonts. We aim to limit data sharing to what is needed to operate the Site and respond to you.</p>
<h2>Analytics</h2>
<p>When enabled, we use Google Analytics to understand how visitors find and use this Site &mdash; which pages are read, and whether people call or submit a form. Google Analytics sets cookies and receives your IP address, device and browser type, and the pages you view. We use it in aggregate to improve the Site.</p><p>We do not send Google Analytics your name, phone number, email address or any information you type into a form. You can opt out across all sites using Google&rsquo;s <a href="https://tools.google.com/dlpage/gaoptout" rel="nofollow noopener" target="_blank">browser opt-out add-on</a>, or by using your browser&rsquo;s cookie controls.</p>
<h2>Your choices</h2>
<p>You can opt out of further contact at any time by telling us, replying STOP to texts, or unsubscribing from emails. To request that we delete your information, contact us using the details below.</p>
<h2>Data security</h2>
<p>We take reasonable measures to protect the information you share, but no method of transmission over the internet is completely secure.</p>
<h2>Children</h2>
<p>The Site is intended for adults making Medicare decisions and is not directed to children under 13.</p>
<h2>Contact us</h2>
<p>Questions about this policy? Call <a href="tel:[[TEL]]"><strong>[[PHONE]]</strong></a>, email <a href="mailto:[[EMAIL]]">[[EMAIL]]</a>, or use the form on our <a href="/">home page</a>.</p>
<p style="font-size:.85rem;color:var(--ink-soft)">ECOS Medicare Solutions is not connected with or endorsed by the U.S. government or the federal Medicare program. This is a solicitation for insurance.</p>
"""

TERMS_BODY = """<p style="color:var(--ink-soft)"><em>Last updated: September 13, 2026. This document is provided as a starting template and should be reviewed by your attorney before launch.</em></p>
<p>By using the Ohio section of ecosinsurancesolutions.com (the "Site"), operated by ECOS Medicare Solutions, you agree to these Terms of Use.</p>
<h2>Informational purpose</h2>
<p>The Site provides general information about Medicare to help you make decisions. It is not legal, tax or medical advice, and it is not a substitute for the official Medicare program or for Ohio&rsquo;s free counseling program, OSHIIP (the Ohio Senior Health Insurance Information Program, 800-686-1578). Medicare plan availability, costs and rules change and vary by county.</p>
<h2>Insurance offered through a licensed agent</h2>
<p>Insurance products referenced on the Site are offered through a licensed insurance agent (Darin Weidauer, Ohio insurance license #1616139, NPN 18580338). Enrollment is subject to plan terms and eligibility. We do not offer every plan available in your area. Where a retirement system or employer plan requires enrollment through its own connector, the Site does not replace that process.</p>
<h2>No guarantee of accuracy</h2>
<p>We work to keep figures current and cite the year and source, but we do not warrant that all information is complete, current or error-free. Always confirm details with the official sources noted on the Site.</p>
<h2>External links</h2>
<p>The Site links to third-party websites (such as Medicare.gov, insurance.ohio.gov and medicaid.ohio.gov) and to other sections and sites operated by ECOS Medicare Solutions. We are not responsible for the content or practices of third-party sites.</p>
<h2>Limitation of liability</h2>
<p>To the fullest extent permitted by law, ECOS Medicare Solutions is not liable for any damages arising from your use of the Site.</p>
<h2>Governing law</h2>
<p>These Terms are governed by the laws of the State of Ohio.</p>
<h2>Contact us</h2>
<p>Questions? Call <a href="tel:[[TEL]]"><strong>[[PHONE]]</strong></a> or use the form on our <a href="/">home page</a>.</p>
<p style="font-size:.85rem;color:var(--ink-soft)">ECOS Medicare Solutions is not connected with or endorsed by the U.S. government or the federal Medicare program. This is a solicitation for insurance.</p>
"""
